-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity compute_slave_compute_slave_Pipeline_compute_rows_VITIS_LOOP_69_5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    REG1_V_6_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG1_V_4_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG1_V_2_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG1_V_1_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_6_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_4_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_2_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_1_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG1_V_7_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG1_V_9_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG1_V_11_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG1_V_14_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_7_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_9_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_11_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_14_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG1_V_5_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG1_V_3_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG1_V_12_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG1_V_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_5_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_3_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_12_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG1_V_8_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG1_V_10_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG1_V_13_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG1_V_15_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_8_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_10_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_13_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_15_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    result_out_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    result_out_ce0 : OUT STD_LOGIC;
    result_out_we0 : OUT STD_LOGIC;
    result_out_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of compute_slave_compute_slave_Pipeline_compute_rows_VITIS_LOOP_69_5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln68_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln68_fu_393_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln68_reg_697 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln68_reg_697_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln68_reg_697_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln68_reg_697_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_12_fu_397_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_12_reg_704 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_12_reg_704_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_12_reg_704_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_12_reg_704_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_562_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_568_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln74_fu_557_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal com_fu_112 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln69_fu_473_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_com_load : STD_LOGIC_VECTOR (2 downto 0);
    signal i_fu_116 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln68_1_fu_385_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten13_fu_120 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln68_fu_353_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_indvar_flatten13_load : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln69_fu_365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln68_1_fu_379_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln68_fu_371_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_1_fu_401_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_1_fu_419_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_2_fu_437_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_2_fu_455_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_fu_494_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_507_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_3_fu_520_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_3_fu_533_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_583_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_574_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln74_3_fu_551_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_562_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_562_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_568_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_568_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_574_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_574_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_583_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_583_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_562_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_562_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_568_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_568_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_574_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_574_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_583_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_583_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component compute_slave_mux_42_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component compute_slave_mul_mul_16ns_16ns_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component compute_slave_mac_muladd_16ns_16ns_32ns_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component compute_slave_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_42_16_1_1_U35 : component compute_slave_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG1_V_7_reload,
        din1 => REG1_V_9_reload,
        din2 => REG1_V_11_reload,
        din3 => REG1_V_14_reload,
        din4 => trunc_ln68_fu_393_p1,
        dout => tmp_7_1_fu_401_p6);

    mux_42_16_1_1_U36 : component compute_slave_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG2_V_7_reload,
        din1 => REG2_V_9_reload,
        din2 => REG2_V_11_reload,
        din3 => REG2_V_14_reload,
        din4 => empty_12_fu_397_p1,
        dout => tmp_2_1_fu_419_p6);

    mux_42_16_1_1_U37 : component compute_slave_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG1_V_5_reload,
        din1 => REG1_V_3_reload,
        din2 => REG1_V_12_reload,
        din3 => REG1_V_reload,
        din4 => trunc_ln68_fu_393_p1,
        dout => tmp_7_2_fu_437_p6);

    mux_42_16_1_1_U38 : component compute_slave_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG2_V_5_reload,
        din1 => REG2_V_3_reload,
        din2 => REG2_V_12_reload,
        din3 => REG2_V_reload,
        din4 => empty_12_fu_397_p1,
        dout => tmp_2_2_fu_455_p6);

    mux_42_16_1_1_U39 : component compute_slave_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG1_V_6_reload,
        din1 => REG1_V_4_reload,
        din2 => REG1_V_2_reload,
        din3 => REG1_V_1_reload,
        din4 => trunc_ln68_reg_697,
        dout => tmp_7_fu_494_p6);

    mux_42_16_1_1_U40 : component compute_slave_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG2_V_6_reload,
        din1 => REG2_V_4_reload,
        din2 => REG2_V_2_reload,
        din3 => REG2_V_1_reload,
        din4 => empty_12_reg_704,
        dout => tmp_2_fu_507_p6);

    mux_42_16_1_1_U41 : component compute_slave_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG1_V_8_reload,
        din1 => REG1_V_10_reload,
        din2 => REG1_V_13_reload,
        din3 => REG1_V_15_reload,
        din4 => trunc_ln68_reg_697,
        dout => tmp_7_3_fu_520_p6);

    mux_42_16_1_1_U42 : component compute_slave_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG2_V_8_reload,
        din1 => REG2_V_10_reload,
        din2 => REG2_V_13_reload,
        din3 => REG2_V_15_reload,
        din4 => empty_12_reg_704,
        dout => tmp_2_3_fu_533_p6);

    mul_mul_16ns_16ns_32_4_1_U43 : component compute_slave_mul_mul_16ns_16ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_562_p0,
        din1 => grp_fu_562_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_562_p2);

    mul_mul_16ns_16ns_32_4_1_U44 : component compute_slave_mul_mul_16ns_16ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_568_p0,
        din1 => grp_fu_568_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_568_p2);

    mac_muladd_16ns_16ns_32ns_32_4_1_U45 : component compute_slave_mac_muladd_16ns_16ns_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_574_p0,
        din1 => grp_fu_574_p1,
        din2 => grp_fu_562_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_574_p3);

    mac_muladd_16ns_16ns_32ns_32_4_1_U46 : component compute_slave_mac_muladd_16ns_16ns_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_583_p0,
        din1 => grp_fu_583_p1,
        din2 => grp_fu_568_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_583_p3);

    flow_control_loop_pipe_sequential_init_U : component compute_slave_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    com_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln68_fu_347_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    com_fu_112 <= add_ln69_fu_473_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    com_fu_112 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    i_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln68_fu_347_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_116 <= select_ln68_1_fu_385_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_116 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten13_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln68_fu_347_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten13_fu_120 <= add_ln68_fu_353_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten13_fu_120 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                empty_12_reg_704_pp0_iter1_reg <= empty_12_reg_704;
                trunc_ln68_reg_697_pp0_iter1_reg <= trunc_ln68_reg_697;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                empty_12_reg_704_pp0_iter2_reg <= empty_12_reg_704_pp0_iter1_reg;
                empty_12_reg_704_pp0_iter3_reg <= empty_12_reg_704_pp0_iter2_reg;
                trunc_ln68_reg_697_pp0_iter2_reg <= trunc_ln68_reg_697_pp0_iter1_reg;
                trunc_ln68_reg_697_pp0_iter3_reg <= trunc_ln68_reg_697_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln68_fu_347_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                empty_12_reg_704 <= empty_12_fu_397_p1;
                trunc_ln68_reg_697 <= trunc_ln68_fu_393_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln68_1_fu_379_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv3_1));
    add_ln68_fu_353_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten13_load) + unsigned(ap_const_lv5_1));
    add_ln69_fu_473_p2 <= std_logic_vector(unsigned(select_ln68_fu_371_p3) + unsigned(ap_const_lv3_1));
    add_ln74_3_fu_551_p3 <= (trunc_ln68_reg_697_pp0_iter3_reg & empty_12_reg_704_pp0_iter3_reg);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln68_fu_347_p2)
    begin
        if (((icmp_ln68_fu_347_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_com_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, com_fu_112, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_com_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_com_load <= com_fu_112;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_116)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_116;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten13_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten13_fu_120)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten13_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_indvar_flatten13_load <= indvar_flatten13_fu_120;
        end if; 
    end process;

    empty_12_fu_397_p1 <= select_ln68_fu_371_p3(2 - 1 downto 0);
    grp_fu_562_p0 <= grp_fu_562_p00(16 - 1 downto 0);
    grp_fu_562_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_1_fu_419_p6),32));
    grp_fu_562_p1 <= grp_fu_562_p10(16 - 1 downto 0);
    grp_fu_562_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_1_fu_401_p6),32));
    grp_fu_568_p0 <= grp_fu_568_p00(16 - 1 downto 0);
    grp_fu_568_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_2_fu_455_p6),32));
    grp_fu_568_p1 <= grp_fu_568_p10(16 - 1 downto 0);
    grp_fu_568_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_2_fu_437_p6),32));
    grp_fu_574_p0 <= grp_fu_574_p00(16 - 1 downto 0);
    grp_fu_574_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_507_p6),32));
    grp_fu_574_p1 <= grp_fu_574_p10(16 - 1 downto 0);
    grp_fu_574_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_494_p6),32));
    grp_fu_583_p0 <= grp_fu_583_p00(16 - 1 downto 0);
    grp_fu_583_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_3_fu_533_p6),32));
    grp_fu_583_p1 <= grp_fu_583_p10(16 - 1 downto 0);
    grp_fu_583_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_3_fu_520_p6),32));
    icmp_ln68_fu_347_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten13_load = ap_const_lv5_10) else "0";
    icmp_ln69_fu_365_p2 <= "1" when (ap_sig_allocacmp_com_load = ap_const_lv3_4) else "0";
    result_out_address0 <= zext_ln74_fu_557_p1(4 - 1 downto 0);

    result_out_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            result_out_ce0 <= ap_const_logic_1;
        else 
            result_out_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    result_out_d0 <= std_logic_vector(unsigned(grp_fu_583_p3) + unsigned(grp_fu_574_p3));

    result_out_we0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            result_out_we0 <= ap_const_logic_1;
        else 
            result_out_we0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln68_1_fu_385_p3 <= 
        add_ln68_1_fu_379_p2 when (icmp_ln69_fu_365_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln68_fu_371_p3 <= 
        ap_const_lv3_0 when (icmp_ln69_fu_365_p2(0) = '1') else 
        ap_sig_allocacmp_com_load;
    trunc_ln68_fu_393_p1 <= select_ln68_1_fu_385_p3(2 - 1 downto 0);
    zext_ln74_fu_557_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln74_3_fu_551_p3),64));
end behav;
