// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module compute_slave_compute_slave_Pipeline_compute_rows_VITIS_LOOP_69_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        REG1_V_6_reload,
        REG1_V_4_reload,
        REG1_V_2_reload,
        REG1_V_1_reload,
        REG2_V_6_reload,
        REG2_V_4_reload,
        REG2_V_2_reload,
        REG2_V_1_reload,
        REG1_V_7_reload,
        REG1_V_9_reload,
        REG1_V_11_reload,
        REG1_V_14_reload,
        REG2_V_7_reload,
        REG2_V_9_reload,
        REG2_V_11_reload,
        REG2_V_14_reload,
        REG1_V_5_reload,
        REG1_V_3_reload,
        REG1_V_12_reload,
        REG1_V_reload,
        REG2_V_5_reload,
        REG2_V_3_reload,
        REG2_V_12_reload,
        REG2_V_reload,
        REG1_V_8_reload,
        REG1_V_10_reload,
        REG1_V_13_reload,
        REG1_V_15_reload,
        REG2_V_8_reload,
        REG2_V_10_reload,
        REG2_V_13_reload,
        REG2_V_15_reload,
        result_out_address0,
        result_out_ce0,
        result_out_we0,
        result_out_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] REG1_V_6_reload;
input  [15:0] REG1_V_4_reload;
input  [15:0] REG1_V_2_reload;
input  [15:0] REG1_V_1_reload;
input  [15:0] REG2_V_6_reload;
input  [15:0] REG2_V_4_reload;
input  [15:0] REG2_V_2_reload;
input  [15:0] REG2_V_1_reload;
input  [15:0] REG1_V_7_reload;
input  [15:0] REG1_V_9_reload;
input  [15:0] REG1_V_11_reload;
input  [15:0] REG1_V_14_reload;
input  [15:0] REG2_V_7_reload;
input  [15:0] REG2_V_9_reload;
input  [15:0] REG2_V_11_reload;
input  [15:0] REG2_V_14_reload;
input  [15:0] REG1_V_5_reload;
input  [15:0] REG1_V_3_reload;
input  [15:0] REG1_V_12_reload;
input  [15:0] REG1_V_reload;
input  [15:0] REG2_V_5_reload;
input  [15:0] REG2_V_3_reload;
input  [15:0] REG2_V_12_reload;
input  [15:0] REG2_V_reload;
input  [15:0] REG1_V_8_reload;
input  [15:0] REG1_V_10_reload;
input  [15:0] REG1_V_13_reload;
input  [15:0] REG1_V_15_reload;
input  [15:0] REG2_V_8_reload;
input  [15:0] REG2_V_10_reload;
input  [15:0] REG2_V_13_reload;
input  [15:0] REG2_V_15_reload;
output  [3:0] result_out_address0;
output   result_out_ce0;
output   result_out_we0;
output  [31:0] result_out_d0;

reg ap_idle;
reg result_out_ce0;
reg result_out_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln68_fu_347_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [1:0] trunc_ln68_fu_393_p1;
reg   [1:0] trunc_ln68_reg_697;
reg   [1:0] trunc_ln68_reg_697_pp0_iter1_reg;
reg   [1:0] trunc_ln68_reg_697_pp0_iter2_reg;
reg   [1:0] trunc_ln68_reg_697_pp0_iter3_reg;
wire   [1:0] empty_12_fu_397_p1;
reg   [1:0] empty_12_reg_704;
reg   [1:0] empty_12_reg_704_pp0_iter1_reg;
reg   [1:0] empty_12_reg_704_pp0_iter2_reg;
reg   [1:0] empty_12_reg_704_pp0_iter3_reg;
wire   [31:0] grp_fu_562_p2;
wire   [31:0] grp_fu_568_p2;
wire   [63:0] zext_ln74_fu_557_p1;
wire    ap_block_pp0_stage0;
reg   [2:0] com_fu_112;
wire   [2:0] add_ln69_fu_473_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_com_load;
reg   [2:0] i_fu_116;
wire   [2:0] select_ln68_1_fu_385_p3;
reg   [2:0] ap_sig_allocacmp_i_load;
reg   [4:0] indvar_flatten13_fu_120;
wire   [4:0] add_ln68_fu_353_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten13_load;
wire   [0:0] icmp_ln69_fu_365_p2;
wire   [2:0] add_ln68_1_fu_379_p2;
wire   [2:0] select_ln68_fu_371_p3;
wire   [15:0] tmp_7_1_fu_401_p6;
wire   [15:0] tmp_2_1_fu_419_p6;
wire   [15:0] tmp_7_2_fu_437_p6;
wire   [15:0] tmp_2_2_fu_455_p6;
wire   [15:0] tmp_7_fu_494_p6;
wire   [15:0] tmp_2_fu_507_p6;
wire   [15:0] tmp_7_3_fu_520_p6;
wire   [15:0] tmp_2_3_fu_533_p6;
wire   [31:0] grp_fu_583_p3;
wire   [31:0] grp_fu_574_p3;
wire   [3:0] add_ln74_3_fu_551_p3;
wire   [15:0] grp_fu_562_p0;
wire   [15:0] grp_fu_562_p1;
wire   [15:0] grp_fu_568_p0;
wire   [15:0] grp_fu_568_p1;
wire   [15:0] grp_fu_574_p0;
wire   [15:0] grp_fu_574_p1;
wire   [15:0] grp_fu_583_p0;
wire   [15:0] grp_fu_583_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [31:0] grp_fu_562_p00;
wire   [31:0] grp_fu_562_p10;
wire   [31:0] grp_fu_568_p00;
wire   [31:0] grp_fu_568_p10;
wire   [31:0] grp_fu_574_p00;
wire   [31:0] grp_fu_574_p10;
wire   [31:0] grp_fu_583_p00;
wire   [31:0] grp_fu_583_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

compute_slave_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U35(
    .din0(REG1_V_7_reload),
    .din1(REG1_V_9_reload),
    .din2(REG1_V_11_reload),
    .din3(REG1_V_14_reload),
    .din4(trunc_ln68_fu_393_p1),
    .dout(tmp_7_1_fu_401_p6)
);

compute_slave_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U36(
    .din0(REG2_V_7_reload),
    .din1(REG2_V_9_reload),
    .din2(REG2_V_11_reload),
    .din3(REG2_V_14_reload),
    .din4(empty_12_fu_397_p1),
    .dout(tmp_2_1_fu_419_p6)
);

compute_slave_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U37(
    .din0(REG1_V_5_reload),
    .din1(REG1_V_3_reload),
    .din2(REG1_V_12_reload),
    .din3(REG1_V_reload),
    .din4(trunc_ln68_fu_393_p1),
    .dout(tmp_7_2_fu_437_p6)
);

compute_slave_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U38(
    .din0(REG2_V_5_reload),
    .din1(REG2_V_3_reload),
    .din2(REG2_V_12_reload),
    .din3(REG2_V_reload),
    .din4(empty_12_fu_397_p1),
    .dout(tmp_2_2_fu_455_p6)
);

compute_slave_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U39(
    .din0(REG1_V_6_reload),
    .din1(REG1_V_4_reload),
    .din2(REG1_V_2_reload),
    .din3(REG1_V_1_reload),
    .din4(trunc_ln68_reg_697),
    .dout(tmp_7_fu_494_p6)
);

compute_slave_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U40(
    .din0(REG2_V_6_reload),
    .din1(REG2_V_4_reload),
    .din2(REG2_V_2_reload),
    .din3(REG2_V_1_reload),
    .din4(empty_12_reg_704),
    .dout(tmp_2_fu_507_p6)
);

compute_slave_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U41(
    .din0(REG1_V_8_reload),
    .din1(REG1_V_10_reload),
    .din2(REG1_V_13_reload),
    .din3(REG1_V_15_reload),
    .din4(trunc_ln68_reg_697),
    .dout(tmp_7_3_fu_520_p6)
);

compute_slave_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U42(
    .din0(REG2_V_8_reload),
    .din1(REG2_V_10_reload),
    .din2(REG2_V_13_reload),
    .din3(REG2_V_15_reload),
    .din4(empty_12_reg_704),
    .dout(tmp_2_3_fu_533_p6)
);

compute_slave_mul_mul_16ns_16ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16ns_16ns_32_4_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_562_p0),
    .din1(grp_fu_562_p1),
    .ce(1'b1),
    .dout(grp_fu_562_p2)
);

compute_slave_mul_mul_16ns_16ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16ns_16ns_32_4_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_568_p0),
    .din1(grp_fu_568_p1),
    .ce(1'b1),
    .dout(grp_fu_568_p2)
);

compute_slave_mac_muladd_16ns_16ns_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16ns_16ns_32ns_32_4_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_574_p0),
    .din1(grp_fu_574_p1),
    .din2(grp_fu_562_p2),
    .ce(1'b1),
    .dout(grp_fu_574_p3)
);

compute_slave_mac_muladd_16ns_16ns_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16ns_16ns_32ns_32_4_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_583_p0),
    .din1(grp_fu_583_p1),
    .din2(grp_fu_568_p2),
    .ce(1'b1),
    .dout(grp_fu_583_p3)
);

compute_slave_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln68_fu_347_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            com_fu_112 <= add_ln69_fu_473_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            com_fu_112 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln68_fu_347_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_116 <= select_ln68_1_fu_385_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_116 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln68_fu_347_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten13_fu_120 <= add_ln68_fu_353_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten13_fu_120 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        empty_12_reg_704_pp0_iter1_reg <= empty_12_reg_704;
        trunc_ln68_reg_697_pp0_iter1_reg <= trunc_ln68_reg_697;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        empty_12_reg_704_pp0_iter2_reg <= empty_12_reg_704_pp0_iter1_reg;
        empty_12_reg_704_pp0_iter3_reg <= empty_12_reg_704_pp0_iter2_reg;
        trunc_ln68_reg_697_pp0_iter2_reg <= trunc_ln68_reg_697_pp0_iter1_reg;
        trunc_ln68_reg_697_pp0_iter3_reg <= trunc_ln68_reg_697_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln68_fu_347_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_12_reg_704 <= empty_12_fu_397_p1;
        trunc_ln68_reg_697 <= trunc_ln68_fu_393_p1;
    end
end

always @ (*) begin
    if (((icmp_ln68_fu_347_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_com_load = 3'd0;
    end else begin
        ap_sig_allocacmp_com_load = com_fu_112;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_load = 3'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_116;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten13_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten13_load = indvar_flatten13_fu_120;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        result_out_ce0 = 1'b1;
    end else begin
        result_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        result_out_we0 = 1'b1;
    end else begin
        result_out_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln68_1_fu_379_p2 = (ap_sig_allocacmp_i_load + 3'd1);

assign add_ln68_fu_353_p2 = (ap_sig_allocacmp_indvar_flatten13_load + 5'd1);

assign add_ln69_fu_473_p2 = (select_ln68_fu_371_p3 + 3'd1);

assign add_ln74_3_fu_551_p3 = {{trunc_ln68_reg_697_pp0_iter3_reg}, {empty_12_reg_704_pp0_iter3_reg}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_12_fu_397_p1 = select_ln68_fu_371_p3[1:0];

assign grp_fu_562_p0 = grp_fu_562_p00;

assign grp_fu_562_p00 = tmp_2_1_fu_419_p6;

assign grp_fu_562_p1 = grp_fu_562_p10;

assign grp_fu_562_p10 = tmp_7_1_fu_401_p6;

assign grp_fu_568_p0 = grp_fu_568_p00;

assign grp_fu_568_p00 = tmp_2_2_fu_455_p6;

assign grp_fu_568_p1 = grp_fu_568_p10;

assign grp_fu_568_p10 = tmp_7_2_fu_437_p6;

assign grp_fu_574_p0 = grp_fu_574_p00;

assign grp_fu_574_p00 = tmp_2_fu_507_p6;

assign grp_fu_574_p1 = grp_fu_574_p10;

assign grp_fu_574_p10 = tmp_7_fu_494_p6;

assign grp_fu_583_p0 = grp_fu_583_p00;

assign grp_fu_583_p00 = tmp_2_3_fu_533_p6;

assign grp_fu_583_p1 = grp_fu_583_p10;

assign grp_fu_583_p10 = tmp_7_3_fu_520_p6;

assign icmp_ln68_fu_347_p2 = ((ap_sig_allocacmp_indvar_flatten13_load == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_365_p2 = ((ap_sig_allocacmp_com_load == 3'd4) ? 1'b1 : 1'b0);

assign result_out_address0 = zext_ln74_fu_557_p1;

assign result_out_d0 = (grp_fu_583_p3 + grp_fu_574_p3);

assign select_ln68_1_fu_385_p3 = ((icmp_ln69_fu_365_p2[0:0] == 1'b1) ? add_ln68_1_fu_379_p2 : ap_sig_allocacmp_i_load);

assign select_ln68_fu_371_p3 = ((icmp_ln69_fu_365_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_com_load);

assign trunc_ln68_fu_393_p1 = select_ln68_1_fu_385_p3[1:0];

assign zext_ln74_fu_557_p1 = add_ln74_3_fu_551_p3;

endmodule //compute_slave_compute_slave_Pipeline_compute_rows_VITIS_LOOP_69_5
