-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity compute_slave_compute_slave_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    fwd_in2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    fwd_in2_empty_n : IN STD_LOGIC;
    fwd_in2_read : OUT STD_LOGIC;
    REG2_V_15_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_15_out_ap_vld : OUT STD_LOGIC;
    REG2_V_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_out_ap_vld : OUT STD_LOGIC;
    REG2_V_14_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_14_out_ap_vld : OUT STD_LOGIC;
    REG2_V_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_1_out_ap_vld : OUT STD_LOGIC;
    REG2_V_13_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_13_out_ap_vld : OUT STD_LOGIC;
    REG2_V_12_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_12_out_ap_vld : OUT STD_LOGIC;
    REG2_V_11_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_11_out_ap_vld : OUT STD_LOGIC;
    REG2_V_2_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_2_out_ap_vld : OUT STD_LOGIC;
    REG2_V_10_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_10_out_ap_vld : OUT STD_LOGIC;
    REG2_V_3_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_3_out_ap_vld : OUT STD_LOGIC;
    REG2_V_9_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_9_out_ap_vld : OUT STD_LOGIC;
    REG2_V_4_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_4_out_ap_vld : OUT STD_LOGIC;
    REG2_V_8_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_8_out_ap_vld : OUT STD_LOGIC;
    REG2_V_5_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_5_out_ap_vld : OUT STD_LOGIC;
    REG2_V_7_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_7_out_ap_vld : OUT STD_LOGIC;
    REG2_V_6_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG2_V_6_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of compute_slave_compute_slave_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln60_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal fwd_in2_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal j_fu_90 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln61_fu_637_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_94 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln45_1_fu_345_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten6_fu_98 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln60_fu_308_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten6_load : STD_LOGIC_VECTOR (3 downto 0);
    signal REG2_V_6_fu_102 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln63_4_fu_521_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln45_fu_353_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal REG2_V_7_fu_106 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln63_7_fu_545_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG2_V_5_fu_110 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln63_5_fu_529_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG2_V_8_fu_114 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln63_6_fu_537_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG2_V_4_fu_118 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln63_8_fu_457_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG2_V_9_fu_122 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln63_11_fu_481_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG2_V_3_fu_126 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln63_9_fu_465_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG2_V_10_fu_130 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln63_10_fu_473_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG2_V_2_fu_134 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln63_12_fu_393_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG2_V_11_fu_138 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln63_15_fu_417_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG2_V_12_fu_142 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln63_13_fu_401_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG2_V_13_fu_146 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln63_14_fu_409_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG2_V_1_fu_150 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln63_fu_585_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG2_V_14_fu_154 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln63_3_fu_609_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG2_V_fu_158 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln63_1_fu_593_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG2_V_15_fu_162 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln63_2_fu_601_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln61_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln60_1_fu_339_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln45_fu_331_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln63_fu_361_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln63_fu_365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal REG2_V_16_fu_357_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG2_V_17_fu_371_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component compute_slave_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component compute_slave_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_94 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_fu_94 <= select_ln45_1_fu_345_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten6_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln60_fu_302_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten6_fu_98 <= add_ln60_fu_308_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten6_fu_98 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_90 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_fu_90 <= add_ln61_fu_637_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln45_fu_353_p1 = ap_const_lv2_1))) then
                REG2_V_10_fu_130 <= select_ln63_10_fu_473_p3;
                REG2_V_3_fu_126 <= select_ln63_9_fu_465_p3;
                REG2_V_4_fu_118 <= select_ln63_8_fu_457_p3;
                REG2_V_9_fu_122 <= select_ln63_11_fu_481_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln45_fu_353_p1 = ap_const_lv2_2))) then
                REG2_V_11_fu_138 <= select_ln63_15_fu_417_p3;
                REG2_V_12_fu_142 <= select_ln63_13_fu_401_p3;
                REG2_V_13_fu_146 <= select_ln63_14_fu_409_p3;
                REG2_V_2_fu_134 <= select_ln63_12_fu_393_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln45_fu_353_p1 = ap_const_lv2_3))) then
                REG2_V_14_fu_154 <= select_ln63_3_fu_609_p3;
                REG2_V_15_fu_162 <= select_ln63_2_fu_601_p3;
                REG2_V_1_fu_150 <= select_ln63_fu_585_p3;
                REG2_V_fu_158 <= select_ln63_1_fu_593_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln45_fu_353_p1 = ap_const_lv2_0))) then
                REG2_V_5_fu_110 <= select_ln63_5_fu_529_p3;
                REG2_V_6_fu_102 <= select_ln63_4_fu_521_p3;
                REG2_V_7_fu_106 <= select_ln63_7_fu_545_p3;
                REG2_V_8_fu_114 <= select_ln63_6_fu_537_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    REG2_V_10_out <= REG2_V_10_fu_130;

    REG2_V_10_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln60_fu_302_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_fu_302_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            REG2_V_10_out_ap_vld <= ap_const_logic_1;
        else 
            REG2_V_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG2_V_11_out <= REG2_V_11_fu_138;

    REG2_V_11_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln60_fu_302_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_fu_302_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            REG2_V_11_out_ap_vld <= ap_const_logic_1;
        else 
            REG2_V_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG2_V_12_out <= REG2_V_12_fu_142;

    REG2_V_12_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln60_fu_302_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_fu_302_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            REG2_V_12_out_ap_vld <= ap_const_logic_1;
        else 
            REG2_V_12_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG2_V_13_out <= REG2_V_13_fu_146;

    REG2_V_13_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln60_fu_302_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_fu_302_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            REG2_V_13_out_ap_vld <= ap_const_logic_1;
        else 
            REG2_V_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG2_V_14_out <= REG2_V_14_fu_154;

    REG2_V_14_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln60_fu_302_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_fu_302_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            REG2_V_14_out_ap_vld <= ap_const_logic_1;
        else 
            REG2_V_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG2_V_15_out <= REG2_V_15_fu_162;

    REG2_V_15_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln60_fu_302_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_fu_302_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            REG2_V_15_out_ap_vld <= ap_const_logic_1;
        else 
            REG2_V_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG2_V_16_fu_357_p1 <= fwd_in2_dout(16 - 1 downto 0);
    REG2_V_17_fu_371_p4 <= fwd_in2_dout(31 downto 16);
    REG2_V_1_out <= REG2_V_1_fu_150;

    REG2_V_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln60_fu_302_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_fu_302_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            REG2_V_1_out_ap_vld <= ap_const_logic_1;
        else 
            REG2_V_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG2_V_2_out <= REG2_V_2_fu_134;

    REG2_V_2_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln60_fu_302_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_fu_302_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            REG2_V_2_out_ap_vld <= ap_const_logic_1;
        else 
            REG2_V_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG2_V_3_out <= REG2_V_3_fu_126;

    REG2_V_3_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln60_fu_302_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_fu_302_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            REG2_V_3_out_ap_vld <= ap_const_logic_1;
        else 
            REG2_V_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG2_V_4_out <= REG2_V_4_fu_118;

    REG2_V_4_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln60_fu_302_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_fu_302_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            REG2_V_4_out_ap_vld <= ap_const_logic_1;
        else 
            REG2_V_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG2_V_5_out <= REG2_V_5_fu_110;

    REG2_V_5_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln60_fu_302_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_fu_302_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            REG2_V_5_out_ap_vld <= ap_const_logic_1;
        else 
            REG2_V_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG2_V_6_out <= REG2_V_6_fu_102;

    REG2_V_6_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln60_fu_302_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_fu_302_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            REG2_V_6_out_ap_vld <= ap_const_logic_1;
        else 
            REG2_V_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG2_V_7_out <= REG2_V_7_fu_106;

    REG2_V_7_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln60_fu_302_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_fu_302_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            REG2_V_7_out_ap_vld <= ap_const_logic_1;
        else 
            REG2_V_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG2_V_8_out <= REG2_V_8_fu_114;

    REG2_V_8_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln60_fu_302_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_fu_302_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            REG2_V_8_out_ap_vld <= ap_const_logic_1;
        else 
            REG2_V_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG2_V_9_out <= REG2_V_9_fu_122;

    REG2_V_9_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln60_fu_302_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_fu_302_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            REG2_V_9_out_ap_vld <= ap_const_logic_1;
        else 
            REG2_V_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG2_V_out <= REG2_V_fu_158;

    REG2_V_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln60_fu_302_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln60_fu_302_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            REG2_V_out_ap_vld <= ap_const_logic_1;
        else 
            REG2_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln60_1_fu_339_p2 <= std_logic_vector(unsigned(i_fu_94) + unsigned(ap_const_lv3_1));
    add_ln60_fu_308_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten6_load) + unsigned(ap_const_lv4_1));
    add_ln61_fu_637_p2 <= std_logic_vector(unsigned(select_ln45_fu_331_p3) + unsigned(ap_const_lv3_2));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, fwd_in2_empty_n)
    begin
                ap_block_pp0_stage0_01001 <= ((fwd_in2_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, fwd_in2_empty_n)
    begin
                ap_block_pp0_stage0_11001 <= ((fwd_in2_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, fwd_in2_empty_n)
    begin
                ap_block_pp0_stage0_subdone <= ((fwd_in2_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(fwd_in2_empty_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (fwd_in2_empty_n = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln60_fu_302_p2)
    begin
        if (((icmp_ln60_fu_302_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten6_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten6_fu_98)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten6_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten6_load <= indvar_flatten6_fu_98;
        end if; 
    end process;


    fwd_in2_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, fwd_in2_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fwd_in2_blk_n <= fwd_in2_empty_n;
        else 
            fwd_in2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    fwd_in2_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fwd_in2_read <= ap_const_logic_1;
        else 
            fwd_in2_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln60_fu_302_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten6_load = ap_const_lv4_8) else "0";
    icmp_ln61_fu_325_p2 <= "1" when (unsigned(j_fu_90) < unsigned(ap_const_lv3_3)) else "0";
    icmp_ln63_fu_365_p2 <= "1" when (trunc_ln63_fu_361_p1 = ap_const_lv2_0) else "0";
    select_ln45_1_fu_345_p3 <= 
        i_fu_94 when (icmp_ln61_fu_325_p2(0) = '1') else 
        add_ln60_1_fu_339_p2;
    select_ln45_fu_331_p3 <= 
        j_fu_90 when (icmp_ln61_fu_325_p2(0) = '1') else 
        ap_const_lv3_0;
    select_ln63_10_fu_473_p3 <= 
        REG2_V_10_fu_130 when (icmp_ln63_fu_365_p2(0) = '1') else 
        REG2_V_17_fu_371_p4;
    select_ln63_11_fu_481_p3 <= 
        REG2_V_17_fu_371_p4 when (icmp_ln63_fu_365_p2(0) = '1') else 
        REG2_V_9_fu_122;
    select_ln63_12_fu_393_p3 <= 
        REG2_V_16_fu_357_p1 when (icmp_ln63_fu_365_p2(0) = '1') else 
        REG2_V_2_fu_134;
    select_ln63_13_fu_401_p3 <= 
        REG2_V_12_fu_142 when (icmp_ln63_fu_365_p2(0) = '1') else 
        REG2_V_16_fu_357_p1;
    select_ln63_14_fu_409_p3 <= 
        REG2_V_13_fu_146 when (icmp_ln63_fu_365_p2(0) = '1') else 
        REG2_V_17_fu_371_p4;
    select_ln63_15_fu_417_p3 <= 
        REG2_V_17_fu_371_p4 when (icmp_ln63_fu_365_p2(0) = '1') else 
        REG2_V_11_fu_138;
    select_ln63_1_fu_593_p3 <= 
        REG2_V_fu_158 when (icmp_ln63_fu_365_p2(0) = '1') else 
        REG2_V_16_fu_357_p1;
    select_ln63_2_fu_601_p3 <= 
        REG2_V_15_fu_162 when (icmp_ln63_fu_365_p2(0) = '1') else 
        REG2_V_17_fu_371_p4;
    select_ln63_3_fu_609_p3 <= 
        REG2_V_17_fu_371_p4 when (icmp_ln63_fu_365_p2(0) = '1') else 
        REG2_V_14_fu_154;
    select_ln63_4_fu_521_p3 <= 
        REG2_V_16_fu_357_p1 when (icmp_ln63_fu_365_p2(0) = '1') else 
        REG2_V_6_fu_102;
    select_ln63_5_fu_529_p3 <= 
        REG2_V_5_fu_110 when (icmp_ln63_fu_365_p2(0) = '1') else 
        REG2_V_16_fu_357_p1;
    select_ln63_6_fu_537_p3 <= 
        REG2_V_8_fu_114 when (icmp_ln63_fu_365_p2(0) = '1') else 
        REG2_V_17_fu_371_p4;
    select_ln63_7_fu_545_p3 <= 
        REG2_V_17_fu_371_p4 when (icmp_ln63_fu_365_p2(0) = '1') else 
        REG2_V_7_fu_106;
    select_ln63_8_fu_457_p3 <= 
        REG2_V_16_fu_357_p1 when (icmp_ln63_fu_365_p2(0) = '1') else 
        REG2_V_4_fu_118;
    select_ln63_9_fu_465_p3 <= 
        REG2_V_3_fu_126 when (icmp_ln63_fu_365_p2(0) = '1') else 
        REG2_V_16_fu_357_p1;
    select_ln63_fu_585_p3 <= 
        REG2_V_16_fu_357_p1 when (icmp_ln63_fu_365_p2(0) = '1') else 
        REG2_V_1_fu_150;
    trunc_ln45_fu_353_p1 <= select_ln45_1_fu_345_p3(2 - 1 downto 0);
    trunc_ln63_fu_361_p1 <= select_ln45_fu_331_p3(2 - 1 downto 0);
end behav;
