-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity compute2in_compute2in_Pipeline_VITIS_LOOP_66_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    REG_V_31 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_30 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_29 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_28 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_27 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_26 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_25 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_24 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_23 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_22 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_21 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_20 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_19 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_18 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_17 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_16 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_15 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_14 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_13 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_12 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_11 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_10 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_9 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_8 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_7 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_6 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_5 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_4 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_3 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_2 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V : IN STD_LOGIC_VECTOR (15 downto 0);
    i_cast : IN STD_LOGIC_VECTOR (1 downto 0);
    buffer_a_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buffer_a_ce0 : OUT STD_LOGIC;
    buffer_a_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    REG_V_63_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_63_out_ap_vld : OUT STD_LOGIC;
    REG_V_62_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_62_out_ap_vld : OUT STD_LOGIC;
    REG_V_61_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_61_out_ap_vld : OUT STD_LOGIC;
    REG_V_60_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_60_out_ap_vld : OUT STD_LOGIC;
    REG_V_59_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_59_out_ap_vld : OUT STD_LOGIC;
    REG_V_58_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_58_out_ap_vld : OUT STD_LOGIC;
    REG_V_57_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_57_out_ap_vld : OUT STD_LOGIC;
    REG_V_56_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_56_out_ap_vld : OUT STD_LOGIC;
    REG_V_55_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_55_out_ap_vld : OUT STD_LOGIC;
    REG_V_54_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_54_out_ap_vld : OUT STD_LOGIC;
    REG_V_53_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_53_out_ap_vld : OUT STD_LOGIC;
    REG_V_52_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_52_out_ap_vld : OUT STD_LOGIC;
    REG_V_51_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_51_out_ap_vld : OUT STD_LOGIC;
    REG_V_50_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_50_out_ap_vld : OUT STD_LOGIC;
    REG_V_49_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_49_out_ap_vld : OUT STD_LOGIC;
    REG_V_48_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_48_out_ap_vld : OUT STD_LOGIC;
    REG_V_47_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_47_out_ap_vld : OUT STD_LOGIC;
    REG_V_46_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_46_out_ap_vld : OUT STD_LOGIC;
    REG_V_45_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_45_out_ap_vld : OUT STD_LOGIC;
    REG_V_44_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_44_out_ap_vld : OUT STD_LOGIC;
    REG_V_43_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_43_out_ap_vld : OUT STD_LOGIC;
    REG_V_42_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_42_out_ap_vld : OUT STD_LOGIC;
    REG_V_41_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_41_out_ap_vld : OUT STD_LOGIC;
    REG_V_40_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_40_out_ap_vld : OUT STD_LOGIC;
    REG_V_39_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_39_out_ap_vld : OUT STD_LOGIC;
    REG_V_38_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_38_out_ap_vld : OUT STD_LOGIC;
    REG_V_37_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_37_out_ap_vld : OUT STD_LOGIC;
    REG_V_36_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_36_out_ap_vld : OUT STD_LOGIC;
    REG_V_35_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_35_out_ap_vld : OUT STD_LOGIC;
    REG_V_34_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_34_out_ap_vld : OUT STD_LOGIC;
    REG_V_33_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_33_out_ap_vld : OUT STD_LOGIC;
    REG_V_32_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    REG_V_32_out_ap_vld : OUT STD_LOGIC;
    self_sum_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    self_sum_V_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of compute2in_compute2in_Pipeline_VITIS_LOOP_66_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv34_0 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln66_fu_937_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_cast_read_reg_1927 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln66_reg_1931 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_reg_1931_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_reg_1931_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_reg_1931_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln68_fu_949_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln68_reg_1935 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln186_16_fu_1481_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_4_fu_1489_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_4_reg_1986 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_4_reg_1986_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln68_fu_961_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal self_sum_V_fu_186 : STD_LOGIC_VECTOR (33 downto 0);
    signal self_sum_V_3_fu_1509_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal fe_fu_190 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln66_fu_943_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_fe_1 : STD_LOGIC_VECTOR (1 downto 0);
    signal REG_V_32_fu_194 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_73_fu_1268_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_33_fu_198 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln75_3_fu_1282_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_34_fu_202 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_72_fu_1261_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_35_fu_206 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln75_2_fu_1275_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_36_fu_210 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln76_3_fu_1296_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_37_fu_214 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln77_3_fu_1310_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_38_fu_218 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln76_2_fu_1289_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_39_fu_222 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln77_2_fu_1303_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_40_fu_226 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_75_fu_1148_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_41_fu_230 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln75_5_fu_1162_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_42_fu_234 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_74_fu_1141_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_43_fu_238 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln75_4_fu_1155_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_44_fu_242 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln76_5_fu_1176_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_45_fu_246 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln77_5_fu_1190_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_46_fu_250 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln76_4_fu_1169_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_47_fu_254 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln77_4_fu_1183_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_48_fu_258 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_79_fu_1028_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_49_fu_262 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_82_fu_1042_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_50_fu_266 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_78_fu_1021_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_51_fu_270 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_83_fu_1035_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_52_fu_274 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_80_fu_1056_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_53_fu_278 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln77_7_fu_1070_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_54_fu_282 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_81_fu_1049_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_55_fu_286 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln77_6_fu_1063_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_56_fu_290 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_66_fu_1388_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_57_fu_294 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln75_1_fu_1402_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_58_fu_298 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_65_fu_1381_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_59_fu_302 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln75_fu_1395_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_60_fu_306 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln76_1_fu_1416_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_61_fu_310 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln77_1_fu_1430_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_62_fu_314 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln76_fu_1409_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_63_fu_318 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln77_fu_1423_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal add_ln_fu_953_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_985_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal lhs_fu_971_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal lhs_1_fu_975_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal rhs_fu_993_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_V_4_fu_1489_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_4_fu_1489_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1648_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln840_fu_1506_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_1648_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_1648_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1648_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_1648_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1648_p20 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_4_fu_1489_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_928 : BOOLEAN;
    signal ap_condition_931 : BOOLEAN;
    signal ap_condition_934 : BOOLEAN;
    signal ap_condition_937 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component compute2in_mul_1ns_16ns_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component compute2in_mac_muladd_1ns_16ns_17ns_33_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (32 downto 0) );
    end component;


    component compute2in_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_1ns_16ns_32_1_1_U1 : component compute2in_mul_1ns_16ns_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        din0 => ret_V_4_fu_1489_p0,
        din1 => ret_V_4_fu_1489_p1,
        dout => ret_V_4_fu_1489_p2);

    mac_muladd_1ns_16ns_17ns_33_4_1_U2 : component compute2in_mac_muladd_1ns_16ns_17ns_33_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 1,
        din1_WIDTH => 16,
        din2_WIDTH => 17,
        dout_WIDTH => 33)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1648_p0,
        din1 => grp_fu_1648_p1,
        din2 => grp_fu_1648_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1648_p3);

    flow_control_loop_pipe_sequential_init_U : component compute2in_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    REG_V_32_fu_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_32_fu_194 <= REG_V;
                elsif ((ap_const_boolean_1 = ap_condition_928)) then 
                    REG_V_32_fu_194 <= REG_V_73_fu_1268_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_33_fu_198_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_33_fu_198 <= REG_V_1;
                elsif ((ap_const_boolean_1 = ap_condition_928)) then 
                    REG_V_33_fu_198 <= select_ln75_3_fu_1282_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_34_fu_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_34_fu_202 <= REG_V_2;
                elsif ((ap_const_boolean_1 = ap_condition_928)) then 
                    REG_V_34_fu_202 <= REG_V_72_fu_1261_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_35_fu_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_35_fu_206 <= REG_V_3;
                elsif ((ap_const_boolean_1 = ap_condition_928)) then 
                    REG_V_35_fu_206 <= select_ln75_2_fu_1275_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_36_fu_210_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_36_fu_210 <= REG_V_4;
                elsif ((ap_const_boolean_1 = ap_condition_928)) then 
                    REG_V_36_fu_210 <= select_ln76_3_fu_1296_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_37_fu_214_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_37_fu_214 <= REG_V_5;
                elsif ((ap_const_boolean_1 = ap_condition_928)) then 
                    REG_V_37_fu_214 <= select_ln77_3_fu_1310_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_38_fu_218_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_38_fu_218 <= REG_V_6;
                elsif ((ap_const_boolean_1 = ap_condition_928)) then 
                    REG_V_38_fu_218 <= select_ln76_2_fu_1289_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_39_fu_222_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_39_fu_222 <= REG_V_7;
                elsif ((ap_const_boolean_1 = ap_condition_928)) then 
                    REG_V_39_fu_222 <= select_ln77_2_fu_1303_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_40_fu_226_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_40_fu_226 <= REG_V_8;
                elsif ((ap_const_boolean_1 = ap_condition_931)) then 
                    REG_V_40_fu_226 <= REG_V_75_fu_1148_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_41_fu_230_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_41_fu_230 <= REG_V_9;
                elsif ((ap_const_boolean_1 = ap_condition_931)) then 
                    REG_V_41_fu_230 <= select_ln75_5_fu_1162_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_42_fu_234_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_42_fu_234 <= REG_V_10;
                elsif ((ap_const_boolean_1 = ap_condition_931)) then 
                    REG_V_42_fu_234 <= REG_V_74_fu_1141_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_43_fu_238_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_43_fu_238 <= REG_V_11;
                elsif ((ap_const_boolean_1 = ap_condition_931)) then 
                    REG_V_43_fu_238 <= select_ln75_4_fu_1155_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_44_fu_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_44_fu_242 <= REG_V_12;
                elsif ((ap_const_boolean_1 = ap_condition_931)) then 
                    REG_V_44_fu_242 <= select_ln76_5_fu_1176_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_45_fu_246_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_45_fu_246 <= REG_V_13;
                elsif ((ap_const_boolean_1 = ap_condition_931)) then 
                    REG_V_45_fu_246 <= select_ln77_5_fu_1190_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_46_fu_250_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_46_fu_250 <= REG_V_14;
                elsif ((ap_const_boolean_1 = ap_condition_931)) then 
                    REG_V_46_fu_250 <= select_ln76_4_fu_1169_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_47_fu_254_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_47_fu_254 <= REG_V_15;
                elsif ((ap_const_boolean_1 = ap_condition_931)) then 
                    REG_V_47_fu_254 <= select_ln77_4_fu_1183_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_48_fu_258_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_48_fu_258 <= REG_V_16;
                elsif ((ap_const_boolean_1 = ap_condition_934)) then 
                    REG_V_48_fu_258 <= REG_V_79_fu_1028_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_49_fu_262_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_49_fu_262 <= REG_V_17;
                elsif ((ap_const_boolean_1 = ap_condition_934)) then 
                    REG_V_49_fu_262 <= REG_V_82_fu_1042_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_50_fu_266_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_50_fu_266 <= REG_V_18;
                elsif ((ap_const_boolean_1 = ap_condition_934)) then 
                    REG_V_50_fu_266 <= REG_V_78_fu_1021_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_51_fu_270_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_51_fu_270 <= REG_V_19;
                elsif ((ap_const_boolean_1 = ap_condition_934)) then 
                    REG_V_51_fu_270 <= REG_V_83_fu_1035_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_52_fu_274_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_52_fu_274 <= REG_V_20;
                elsif ((ap_const_boolean_1 = ap_condition_934)) then 
                    REG_V_52_fu_274 <= REG_V_80_fu_1056_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_53_fu_278_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_53_fu_278 <= REG_V_21;
                elsif ((ap_const_boolean_1 = ap_condition_934)) then 
                    REG_V_53_fu_278 <= select_ln77_7_fu_1070_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_54_fu_282_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_54_fu_282 <= REG_V_22;
                elsif ((ap_const_boolean_1 = ap_condition_934)) then 
                    REG_V_54_fu_282 <= REG_V_81_fu_1049_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_55_fu_286_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_55_fu_286 <= REG_V_23;
                elsif ((ap_const_boolean_1 = ap_condition_934)) then 
                    REG_V_55_fu_286 <= select_ln77_6_fu_1063_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_56_fu_290_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_56_fu_290 <= REG_V_24;
                elsif ((ap_const_boolean_1 = ap_condition_937)) then 
                    REG_V_56_fu_290 <= REG_V_66_fu_1388_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_57_fu_294_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_57_fu_294 <= REG_V_25;
                elsif ((ap_const_boolean_1 = ap_condition_937)) then 
                    REG_V_57_fu_294 <= select_ln75_1_fu_1402_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_58_fu_298_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_58_fu_298 <= REG_V_26;
                elsif ((ap_const_boolean_1 = ap_condition_937)) then 
                    REG_V_58_fu_298 <= REG_V_65_fu_1381_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_59_fu_302_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_59_fu_302 <= REG_V_27;
                elsif ((ap_const_boolean_1 = ap_condition_937)) then 
                    REG_V_59_fu_302 <= select_ln75_fu_1395_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_60_fu_306_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_60_fu_306 <= REG_V_28;
                elsif ((ap_const_boolean_1 = ap_condition_937)) then 
                    REG_V_60_fu_306 <= select_ln76_1_fu_1416_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_61_fu_310_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_61_fu_310 <= REG_V_29;
                elsif ((ap_const_boolean_1 = ap_condition_937)) then 
                    REG_V_61_fu_310 <= select_ln77_1_fu_1430_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_62_fu_314_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_62_fu_314 <= REG_V_30;
                elsif ((ap_const_boolean_1 = ap_condition_937)) then 
                    REG_V_62_fu_314 <= select_ln76_fu_1409_p3;
                end if;
            end if; 
        end if;
    end process;

    REG_V_63_fu_318_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    REG_V_63_fu_318 <= REG_V_31;
                elsif ((ap_const_boolean_1 = ap_condition_937)) then 
                    REG_V_63_fu_318 <= select_ln77_fu_1423_p3;
                end if;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter4_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_const_logic_0;
            elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
            end if; 
        end if;
    end process;

    fe_fu_190_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln66_fu_937_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    fe_fu_190 <= add_ln66_fu_943_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    fe_fu_190 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    self_sum_V_fu_186_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    self_sum_V_fu_186 <= ap_const_lv34_0;
                elsif (((icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
                    self_sum_V_fu_186 <= self_sum_V_3_fu_1509_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln66_reg_1931 <= icmp_ln66_fu_937_p2;
                icmp_ln66_reg_1931_pp0_iter1_reg <= icmp_ln66_reg_1931;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln66_reg_1931_pp0_iter2_reg <= icmp_ln66_reg_1931_pp0_iter1_reg;
                icmp_ln66_reg_1931_pp0_iter3_reg <= icmp_ln66_reg_1931_pp0_iter2_reg;
                ret_V_4_reg_1986_pp0_iter2_reg <= ret_V_4_reg_1986;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ret_V_4_reg_1986 <= ret_V_4_fu_1489_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln66_fu_937_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln68_reg_1935 <= trunc_ln68_fu_949_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    REG_V_32_out <= REG_V_32_fu_194;

    REG_V_32_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_32_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_32_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_33_out <= REG_V_33_fu_198;

    REG_V_33_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_33_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_33_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_34_out <= REG_V_34_fu_202;

    REG_V_34_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_34_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_34_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_35_out <= REG_V_35_fu_206;

    REG_V_35_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_35_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_35_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_36_out <= REG_V_36_fu_210;

    REG_V_36_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_36_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_36_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_37_out <= REG_V_37_fu_214;

    REG_V_37_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_37_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_37_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_38_out <= REG_V_38_fu_218;

    REG_V_38_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_38_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_38_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_39_out <= REG_V_39_fu_222;

    REG_V_39_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_39_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_39_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_40_out <= REG_V_40_fu_226;

    REG_V_40_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_40_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_40_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_41_out <= REG_V_41_fu_230;

    REG_V_41_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_41_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_41_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_42_out <= REG_V_42_fu_234;

    REG_V_42_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_42_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_42_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_43_out <= REG_V_43_fu_238;

    REG_V_43_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_43_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_43_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_44_out <= REG_V_44_fu_242;

    REG_V_44_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_44_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_44_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_45_out <= REG_V_45_fu_246;

    REG_V_45_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_45_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_45_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_46_out <= REG_V_46_fu_250;

    REG_V_46_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_46_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_46_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_47_out <= REG_V_47_fu_254;

    REG_V_47_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_47_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_47_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_48_out <= REG_V_48_fu_258;

    REG_V_48_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_48_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_48_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_49_out <= REG_V_49_fu_262;

    REG_V_49_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_49_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_49_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_50_out <= REG_V_50_fu_266;

    REG_V_50_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_50_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_50_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_51_out <= REG_V_51_fu_270;

    REG_V_51_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_51_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_51_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_52_out <= REG_V_52_fu_274;

    REG_V_52_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_52_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_52_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_53_out <= REG_V_53_fu_278;

    REG_V_53_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_53_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_53_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_54_out <= REG_V_54_fu_282;

    REG_V_54_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_54_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_54_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_55_out <= REG_V_55_fu_286;

    REG_V_55_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_55_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_55_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_56_out <= REG_V_56_fu_290;

    REG_V_56_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_56_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_56_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_57_out <= REG_V_57_fu_294;

    REG_V_57_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_57_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_57_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_58_out <= REG_V_58_fu_298;

    REG_V_58_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_58_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_58_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_59_out <= REG_V_59_fu_302;

    REG_V_59_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_59_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_59_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_60_out <= REG_V_60_fu_306;

    REG_V_60_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_60_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_60_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_61_out <= REG_V_61_fu_310;

    REG_V_61_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_61_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_61_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_62_out <= REG_V_62_fu_314;

    REG_V_62_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_62_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_62_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_63_out <= REG_V_63_fu_318;

    REG_V_63_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            REG_V_63_out_ap_vld <= ap_const_logic_1;
        else 
            REG_V_63_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    REG_V_65_fu_1381_p3 <= 
        lhs_fu_971_p1 when (trunc_ln68_reg_1935(0) = '1') else 
        REG_V_58_fu_298;
    REG_V_66_fu_1388_p3 <= 
        REG_V_56_fu_290 when (trunc_ln68_reg_1935(0) = '1') else 
        lhs_fu_971_p1;
    REG_V_72_fu_1261_p3 <= 
        lhs_fu_971_p1 when (trunc_ln68_reg_1935(0) = '1') else 
        REG_V_34_fu_202;
    REG_V_73_fu_1268_p3 <= 
        REG_V_32_fu_194 when (trunc_ln68_reg_1935(0) = '1') else 
        lhs_fu_971_p1;
    REG_V_74_fu_1141_p3 <= 
        lhs_fu_971_p1 when (trunc_ln68_reg_1935(0) = '1') else 
        REG_V_42_fu_234;
    REG_V_75_fu_1148_p3 <= 
        REG_V_40_fu_226 when (trunc_ln68_reg_1935(0) = '1') else 
        lhs_fu_971_p1;
    REG_V_78_fu_1021_p3 <= 
        lhs_fu_971_p1 when (trunc_ln68_reg_1935(0) = '1') else 
        REG_V_50_fu_266;
    REG_V_79_fu_1028_p3 <= 
        REG_V_48_fu_258 when (trunc_ln68_reg_1935(0) = '1') else 
        lhs_fu_971_p1;
    REG_V_80_fu_1056_p3 <= 
        REG_V_52_fu_274 when (trunc_ln68_reg_1935(0) = '1') else 
        rhs_fu_993_p1;
    REG_V_81_fu_1049_p3 <= 
        rhs_fu_993_p1 when (trunc_ln68_reg_1935(0) = '1') else 
        REG_V_54_fu_282;
    REG_V_82_fu_1042_p3 <= 
        REG_V_49_fu_262 when (trunc_ln68_reg_1935(0) = '1') else 
        lhs_1_fu_975_p4;
    REG_V_83_fu_1035_p3 <= 
        lhs_1_fu_975_p4 when (trunc_ln68_reg_1935(0) = '1') else 
        REG_V_51_fu_270;
    add_ln66_fu_943_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_fe_1) + unsigned(ap_const_lv2_1));
    add_ln_fu_953_p3 <= (i_cast & trunc_ln68_fu_949_p1);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_928_assign_proc : process(ap_enable_reg_pp0_iter1, i_cast_read_reg_1927, icmp_ln66_reg_1931)
    begin
                ap_condition_928 <= ((icmp_ln66_reg_1931 = ap_const_lv1_0) and (i_cast_read_reg_1927 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_931_assign_proc : process(ap_enable_reg_pp0_iter1, i_cast_read_reg_1927, icmp_ln66_reg_1931)
    begin
                ap_condition_931 <= ((icmp_ln66_reg_1931 = ap_const_lv1_0) and (i_cast_read_reg_1927 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_934_assign_proc : process(ap_enable_reg_pp0_iter1, i_cast_read_reg_1927, icmp_ln66_reg_1931)
    begin
                ap_condition_934 <= ((icmp_ln66_reg_1931 = ap_const_lv1_0) and (i_cast_read_reg_1927 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_937_assign_proc : process(ap_enable_reg_pp0_iter1, i_cast_read_reg_1927, icmp_ln66_reg_1931)
    begin
                ap_condition_937 <= ((icmp_ln66_reg_1931 = ap_const_lv1_0) and (i_cast_read_reg_1927 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln66_fu_937_p2)
    begin
        if (((icmp_ln66_fu_937_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_fe_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, fe_fu_190)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_fe_1 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_fe_1 <= fe_fu_190;
        end if; 
    end process;

    buffer_a_address0 <= zext_ln68_fu_961_p1(3 - 1 downto 0);

    buffer_a_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_a_ce0 <= ap_const_logic_1;
        else 
            buffer_a_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1648_p0 <= zext_ln186_16_fu_1481_p1(1 - 1 downto 0);
    grp_fu_1648_p1 <= grp_fu_1648_p10(16 - 1 downto 0);
    grp_fu_1648_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lhs_fu_971_p1),32));
    grp_fu_1648_p2 <= grp_fu_1648_p20(17 - 1 downto 0);
    grp_fu_1648_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_V_4_reg_1986_pp0_iter2_reg),33));
    i_cast_read_reg_1927 <= i_cast;
    icmp_ln66_fu_937_p2 <= "1" when (ap_sig_allocacmp_fe_1 = ap_const_lv2_2) else "0";
    lhs_1_fu_975_p4 <= buffer_a_q0(31 downto 16);
    lhs_fu_971_p1 <= buffer_a_q0(16 - 1 downto 0);
    ret_V_4_fu_1489_p0 <= zext_ln186_16_fu_1481_p1(1 - 1 downto 0);
    ret_V_4_fu_1489_p1 <= ret_V_4_fu_1489_p10(16 - 1 downto 0);
    ret_V_4_fu_1489_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lhs_1_fu_975_p4),32));
    rhs_fu_993_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_985_p3),16));
    select_ln75_1_fu_1402_p3 <= 
        REG_V_57_fu_294 when (trunc_ln68_reg_1935(0) = '1') else 
        lhs_1_fu_975_p4;
    select_ln75_2_fu_1275_p3 <= 
        lhs_1_fu_975_p4 when (trunc_ln68_reg_1935(0) = '1') else 
        REG_V_35_fu_206;
    select_ln75_3_fu_1282_p3 <= 
        REG_V_33_fu_198 when (trunc_ln68_reg_1935(0) = '1') else 
        lhs_1_fu_975_p4;
    select_ln75_4_fu_1155_p3 <= 
        lhs_1_fu_975_p4 when (trunc_ln68_reg_1935(0) = '1') else 
        REG_V_43_fu_238;
    select_ln75_5_fu_1162_p3 <= 
        REG_V_41_fu_230 when (trunc_ln68_reg_1935(0) = '1') else 
        lhs_1_fu_975_p4;
    select_ln75_fu_1395_p3 <= 
        lhs_1_fu_975_p4 when (trunc_ln68_reg_1935(0) = '1') else 
        REG_V_59_fu_302;
    select_ln76_1_fu_1416_p3 <= 
        REG_V_60_fu_306 when (trunc_ln68_reg_1935(0) = '1') else 
        rhs_fu_993_p1;
    select_ln76_2_fu_1289_p3 <= 
        rhs_fu_993_p1 when (trunc_ln68_reg_1935(0) = '1') else 
        REG_V_38_fu_218;
    select_ln76_3_fu_1296_p3 <= 
        REG_V_36_fu_210 when (trunc_ln68_reg_1935(0) = '1') else 
        rhs_fu_993_p1;
    select_ln76_4_fu_1169_p3 <= 
        rhs_fu_993_p1 when (trunc_ln68_reg_1935(0) = '1') else 
        REG_V_46_fu_250;
    select_ln76_5_fu_1176_p3 <= 
        REG_V_44_fu_242 when (trunc_ln68_reg_1935(0) = '1') else 
        rhs_fu_993_p1;
    select_ln76_fu_1409_p3 <= 
        rhs_fu_993_p1 when (trunc_ln68_reg_1935(0) = '1') else 
        REG_V_62_fu_314;
    select_ln77_1_fu_1430_p3 <= 
        REG_V_61_fu_310 when (trunc_ln68_reg_1935(0) = '1') else 
        rhs_fu_993_p1;
    select_ln77_2_fu_1303_p3 <= 
        rhs_fu_993_p1 when (trunc_ln68_reg_1935(0) = '1') else 
        REG_V_39_fu_222;
    select_ln77_3_fu_1310_p3 <= 
        REG_V_37_fu_214 when (trunc_ln68_reg_1935(0) = '1') else 
        rhs_fu_993_p1;
    select_ln77_4_fu_1183_p3 <= 
        rhs_fu_993_p1 when (trunc_ln68_reg_1935(0) = '1') else 
        REG_V_47_fu_254;
    select_ln77_5_fu_1190_p3 <= 
        REG_V_45_fu_246 when (trunc_ln68_reg_1935(0) = '1') else 
        rhs_fu_993_p1;
    select_ln77_6_fu_1063_p3 <= 
        rhs_fu_993_p1 when (trunc_ln68_reg_1935(0) = '1') else 
        REG_V_55_fu_286;
    select_ln77_7_fu_1070_p3 <= 
        REG_V_53_fu_278 when (trunc_ln68_reg_1935(0) = '1') else 
        rhs_fu_993_p1;
    select_ln77_fu_1423_p3 <= 
        rhs_fu_993_p1 when (trunc_ln68_reg_1935(0) = '1') else 
        REG_V_63_fu_318;
    self_sum_V_3_fu_1509_p2 <= std_logic_vector(unsigned(zext_ln840_fu_1506_p1) + unsigned(self_sum_V_fu_186));
    self_sum_V_out <= self_sum_V_fu_186(32 - 1 downto 0);

    self_sum_V_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln66_reg_1931_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln66_reg_1931_pp0_iter3_reg = ap_const_lv1_1))) then 
            self_sum_V_out_ap_vld <= ap_const_logic_1;
        else 
            self_sum_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_985_p3 <= buffer_a_q0(31 downto 31);
    trunc_ln68_fu_949_p1 <= ap_sig_allocacmp_fe_1(1 - 1 downto 0);
    zext_ln186_16_fu_1481_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_985_p3),32));
    zext_ln68_fu_961_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln_fu_953_p3),64));
    zext_ln840_fu_1506_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_1648_p3),34));
end behav;
