-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity compute is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    buffer_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    buffer_1_ce0 : OUT STD_LOGIC;
    buffer_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    buffer_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_2_ce0 : OUT STD_LOGIC;
    buffer_2_we0 : OUT STD_LOGIC;
    buffer_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    phase : IN STD_LOGIC;
    fwd_out1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    fwd_out1_full_n : IN STD_LOGIC;
    fwd_out1_write : OUT STD_LOGIC;
    fwd_out2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    fwd_out2_full_n : IN STD_LOGIC;
    fwd_out2_write : OUT STD_LOGIC );
end;


architecture behav of compute is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "compute_compute,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.313000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2355,HLS_SYN_LUT=2119,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZ7computeP6ap_intILi64EEPS_ILi32EEbRN3hls6streamI7ap_uintILi32EELi0EEES9_E4REG : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal phase_read_read_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_1_reg_1478 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal indvars_iv1_load_reg_1484 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln60_1_fu_579_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln60_1_reg_1492 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_23_fu_713_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_23_reg_1593 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln60_fu_573_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_start : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_done : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_idle : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_ready : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_fwd_out1_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_fwd_out1_write : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_fwd_out2_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_fwd_out2_write : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_buffer_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_buffer_1_ce0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_63_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_63_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_62_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_62_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_61_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_61_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_60_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_60_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_59_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_59_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_58_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_58_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_57_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_57_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_56_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_56_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_55_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_55_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_54_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_54_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_53_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_53_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_52_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_52_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_51_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_51_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_50_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_50_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_49_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_49_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_48_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_48_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_47_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_47_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_46_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_46_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_45_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_45_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_44_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_44_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_43_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_43_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_42_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_42_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_41_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_41_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_40_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_40_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_39_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_39_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_38_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_38_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_37_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_37_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_36_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_36_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_35_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_35_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_34_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_34_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_33_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_33_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_32_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_32_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_self_sum_V_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_self_sum_V_out_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_start : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_done : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_idle : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_ready : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_buffer_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_buffer_2_ce0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_buffer_2_we0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_buffer_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_phase : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o_ap_vld : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal self_sum_V_loc_fu_240 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal zext_ln77_fu_883_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal i_fu_104 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln60_fu_888_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal REG_V_fu_108 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_1_fu_112 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_2_fu_116 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_3_fu_120 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_4_fu_124 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_5_fu_128 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_6_fu_132 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_7_fu_136 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_8_fu_140 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_9_fu_144 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_10_fu_148 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_11_fu_152 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_12_fu_156 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_13_fu_160 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_14_fu_164 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_15_fu_168 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_16_fu_172 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_17_fu_176 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_18_fu_180 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_19_fu_184 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_20_fu_188 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_21_fu_192 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_22_fu_196 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_23_fu_200 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_24_fu_204 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_25_fu_208 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_26_fu_212 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_27_fu_216 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_28_fu_220 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_29_fu_224 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_30_fu_228 : STD_LOGIC_VECTOR (15 downto 0);
    signal REG_V_31_fu_232 : STD_LOGIC_VECTOR (15 downto 0);
    signal indvars_iv1_fu_236 : STD_LOGIC_VECTOR (1 downto 0);
    signal dummy_fu_372 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_allocacmp_dummy_1 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln77_fu_870_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_857_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln_fu_877_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component compute_compute_Pipeline_VITIS_LOOP_62_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        fwd_out1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        fwd_out1_full_n : IN STD_LOGIC;
        fwd_out1_write : OUT STD_LOGIC;
        fwd_out2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        fwd_out2_full_n : IN STD_LOGIC;
        fwd_out2_write : OUT STD_LOGIC;
        REG_V_31 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_30 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_29 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_28 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_27 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_26 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_25 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_24 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_23 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_22 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_21 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_20 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_19 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_18 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_17 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_16 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_15 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_14 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_13 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_12 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_11 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_10 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_9 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_8 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_7 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_6 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_5 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_4 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_3 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V : IN STD_LOGIC_VECTOR (15 downto 0);
        i_cast : IN STD_LOGIC_VECTOR (1 downto 0);
        buffer_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        buffer_1_ce0 : OUT STD_LOGIC;
        buffer_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        REG_V_63_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_63_out_ap_vld : OUT STD_LOGIC;
        REG_V_62_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_62_out_ap_vld : OUT STD_LOGIC;
        REG_V_61_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_61_out_ap_vld : OUT STD_LOGIC;
        REG_V_60_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_60_out_ap_vld : OUT STD_LOGIC;
        REG_V_59_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_59_out_ap_vld : OUT STD_LOGIC;
        REG_V_58_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_58_out_ap_vld : OUT STD_LOGIC;
        REG_V_57_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_57_out_ap_vld : OUT STD_LOGIC;
        REG_V_56_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_56_out_ap_vld : OUT STD_LOGIC;
        REG_V_55_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_55_out_ap_vld : OUT STD_LOGIC;
        REG_V_54_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_54_out_ap_vld : OUT STD_LOGIC;
        REG_V_53_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_53_out_ap_vld : OUT STD_LOGIC;
        REG_V_52_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_52_out_ap_vld : OUT STD_LOGIC;
        REG_V_51_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_51_out_ap_vld : OUT STD_LOGIC;
        REG_V_50_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_50_out_ap_vld : OUT STD_LOGIC;
        REG_V_49_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_49_out_ap_vld : OUT STD_LOGIC;
        REG_V_48_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_48_out_ap_vld : OUT STD_LOGIC;
        REG_V_47_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_47_out_ap_vld : OUT STD_LOGIC;
        REG_V_46_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_46_out_ap_vld : OUT STD_LOGIC;
        REG_V_45_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_45_out_ap_vld : OUT STD_LOGIC;
        REG_V_44_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_44_out_ap_vld : OUT STD_LOGIC;
        REG_V_43_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_43_out_ap_vld : OUT STD_LOGIC;
        REG_V_42_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_42_out_ap_vld : OUT STD_LOGIC;
        REG_V_41_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_41_out_ap_vld : OUT STD_LOGIC;
        REG_V_40_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_40_out_ap_vld : OUT STD_LOGIC;
        REG_V_39_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_39_out_ap_vld : OUT STD_LOGIC;
        REG_V_38_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_38_out_ap_vld : OUT STD_LOGIC;
        REG_V_37_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_37_out_ap_vld : OUT STD_LOGIC;
        REG_V_36_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_36_out_ap_vld : OUT STD_LOGIC;
        REG_V_35_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_35_out_ap_vld : OUT STD_LOGIC;
        REG_V_34_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_34_out_ap_vld : OUT STD_LOGIC;
        REG_V_33_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_33_out_ap_vld : OUT STD_LOGIC;
        REG_V_32_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        REG_V_32_out_ap_vld : OUT STD_LOGIC;
        self_sum_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        self_sum_V_out_ap_vld : OUT STD_LOGIC );
    end component;


    component compute_compute_Pipeline_VITIS_LOOP_81_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        i : IN STD_LOGIC_VECTOR (2 downto 0);
        buffer_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        buffer_2_ce0 : OUT STD_LOGIC;
        buffer_2_we0 : OUT STD_LOGIC;
        buffer_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        REG_V_32_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_40_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_48_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_56_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        indvars_iv1 : IN STD_LOGIC_VECTOR (1 downto 0);
        REG_V_36_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_44_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_52_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_60_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_33_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_41_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_49_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_57_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_37_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_45_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_53_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_61_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_34_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_42_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_50_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_58_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_38_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_46_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_54_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_62_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_35_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_43_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_51_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_59_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_39_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_47_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_55_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        REG_V_63_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        i_cast : IN STD_LOGIC_VECTOR (1 downto 0);
        zext_ln60 : IN STD_LOGIC_VECTOR (2 downto 0);
        phase : IN STD_LOGIC_VECTOR (0 downto 0);
        compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_i : IN STD_LOGIC_VECTOR (31 downto 0);
        compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o_ap_vld : OUT STD_LOGIC;
        compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_i : IN STD_LOGIC_VECTOR (31 downto 0);
        compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o_ap_vld : OUT STD_LOGIC;
        compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_i : IN STD_LOGIC_VECTOR (31 downto 0);
        compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o_ap_vld : OUT STD_LOGIC );
    end component;


    component compute_mux_42_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395 : component compute_compute_Pipeline_VITIS_LOOP_62_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_start,
        ap_done => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_done,
        ap_idle => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_idle,
        ap_ready => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_ready,
        fwd_out1_din => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_fwd_out1_din,
        fwd_out1_full_n => fwd_out1_full_n,
        fwd_out1_write => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_fwd_out1_write,
        fwd_out2_din => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_fwd_out2_din,
        fwd_out2_full_n => fwd_out2_full_n,
        fwd_out2_write => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_fwd_out2_write,
        REG_V_31 => REG_V_31_fu_232,
        REG_V_30 => REG_V_30_fu_228,
        REG_V_29 => REG_V_29_fu_224,
        REG_V_28 => REG_V_28_fu_220,
        REG_V_27 => REG_V_27_fu_216,
        REG_V_26 => REG_V_26_fu_212,
        REG_V_25 => REG_V_25_fu_208,
        REG_V_24 => REG_V_24_fu_204,
        REG_V_23 => REG_V_23_fu_200,
        REG_V_22 => REG_V_22_fu_196,
        REG_V_21 => REG_V_21_fu_192,
        REG_V_20 => REG_V_20_fu_188,
        REG_V_19 => REG_V_19_fu_184,
        REG_V_18 => REG_V_18_fu_180,
        REG_V_17 => REG_V_17_fu_176,
        REG_V_16 => REG_V_16_fu_172,
        REG_V_15 => REG_V_15_fu_168,
        REG_V_14 => REG_V_14_fu_164,
        REG_V_13 => REG_V_13_fu_160,
        REG_V_12 => REG_V_12_fu_156,
        REG_V_11 => REG_V_11_fu_152,
        REG_V_10 => REG_V_10_fu_148,
        REG_V_9 => REG_V_9_fu_144,
        REG_V_8 => REG_V_8_fu_140,
        REG_V_7 => REG_V_7_fu_136,
        REG_V_6 => REG_V_6_fu_132,
        REG_V_5 => REG_V_5_fu_128,
        REG_V_4 => REG_V_4_fu_124,
        REG_V_3 => REG_V_3_fu_120,
        REG_V_2 => REG_V_2_fu_116,
        REG_V_1 => REG_V_1_fu_112,
        REG_V => REG_V_fu_108,
        i_cast => empty_23_reg_1593,
        buffer_1_address0 => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_buffer_1_address0,
        buffer_1_ce0 => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_buffer_1_ce0,
        buffer_1_q0 => buffer_1_q0,
        REG_V_63_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_63_out,
        REG_V_63_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_63_out_ap_vld,
        REG_V_62_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_62_out,
        REG_V_62_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_62_out_ap_vld,
        REG_V_61_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_61_out,
        REG_V_61_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_61_out_ap_vld,
        REG_V_60_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_60_out,
        REG_V_60_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_60_out_ap_vld,
        REG_V_59_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_59_out,
        REG_V_59_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_59_out_ap_vld,
        REG_V_58_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_58_out,
        REG_V_58_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_58_out_ap_vld,
        REG_V_57_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_57_out,
        REG_V_57_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_57_out_ap_vld,
        REG_V_56_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_56_out,
        REG_V_56_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_56_out_ap_vld,
        REG_V_55_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_55_out,
        REG_V_55_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_55_out_ap_vld,
        REG_V_54_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_54_out,
        REG_V_54_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_54_out_ap_vld,
        REG_V_53_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_53_out,
        REG_V_53_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_53_out_ap_vld,
        REG_V_52_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_52_out,
        REG_V_52_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_52_out_ap_vld,
        REG_V_51_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_51_out,
        REG_V_51_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_51_out_ap_vld,
        REG_V_50_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_50_out,
        REG_V_50_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_50_out_ap_vld,
        REG_V_49_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_49_out,
        REG_V_49_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_49_out_ap_vld,
        REG_V_48_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_48_out,
        REG_V_48_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_48_out_ap_vld,
        REG_V_47_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_47_out,
        REG_V_47_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_47_out_ap_vld,
        REG_V_46_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_46_out,
        REG_V_46_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_46_out_ap_vld,
        REG_V_45_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_45_out,
        REG_V_45_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_45_out_ap_vld,
        REG_V_44_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_44_out,
        REG_V_44_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_44_out_ap_vld,
        REG_V_43_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_43_out,
        REG_V_43_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_43_out_ap_vld,
        REG_V_42_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_42_out,
        REG_V_42_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_42_out_ap_vld,
        REG_V_41_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_41_out,
        REG_V_41_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_41_out_ap_vld,
        REG_V_40_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_40_out,
        REG_V_40_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_40_out_ap_vld,
        REG_V_39_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_39_out,
        REG_V_39_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_39_out_ap_vld,
        REG_V_38_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_38_out,
        REG_V_38_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_38_out_ap_vld,
        REG_V_37_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_37_out,
        REG_V_37_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_37_out_ap_vld,
        REG_V_36_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_36_out,
        REG_V_36_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_36_out_ap_vld,
        REG_V_35_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_35_out,
        REG_V_35_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_35_out_ap_vld,
        REG_V_34_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_34_out,
        REG_V_34_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_34_out_ap_vld,
        REG_V_33_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_33_out,
        REG_V_33_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_33_out_ap_vld,
        REG_V_32_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_32_out,
        REG_V_32_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_32_out_ap_vld,
        self_sum_V_out => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_self_sum_V_out,
        self_sum_V_out_ap_vld => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_self_sum_V_out_ap_vld);

    grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471 : component compute_compute_Pipeline_VITIS_LOOP_81_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_start,
        ap_done => grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_done,
        ap_idle => grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_idle,
        ap_ready => grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_ready,
        i => i_1_reg_1478,
        buffer_2_address0 => grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_buffer_2_address0,
        buffer_2_ce0 => grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_buffer_2_ce0,
        buffer_2_we0 => grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_buffer_2_we0,
        buffer_2_d0 => grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_buffer_2_d0,
        REG_V_32_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_32_out,
        REG_V_40_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_40_out,
        REG_V_48_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_48_out,
        REG_V_56_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_56_out,
        indvars_iv1 => indvars_iv1_load_reg_1484,
        REG_V_36_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_36_out,
        REG_V_44_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_44_out,
        REG_V_52_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_52_out,
        REG_V_60_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_60_out,
        REG_V_33_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_33_out,
        REG_V_41_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_41_out,
        REG_V_49_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_49_out,
        REG_V_57_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_57_out,
        REG_V_37_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_37_out,
        REG_V_45_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_45_out,
        REG_V_53_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_53_out,
        REG_V_61_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_61_out,
        REG_V_34_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_34_out,
        REG_V_42_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_42_out,
        REG_V_50_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_50_out,
        REG_V_58_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_58_out,
        REG_V_38_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_38_out,
        REG_V_46_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_46_out,
        REG_V_54_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_54_out,
        REG_V_62_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_62_out,
        REG_V_35_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_35_out,
        REG_V_43_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_43_out,
        REG_V_51_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_51_out,
        REG_V_59_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_59_out,
        REG_V_39_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_39_out,
        REG_V_47_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_47_out,
        REG_V_55_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_55_out,
        REG_V_63_reload => grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_63_out,
        i_cast => empty_23_reg_1593,
        zext_ln60 => i_1_reg_1478,
        phase => grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_phase,
        compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_i => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9,
        compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o => grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o,
        compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o_ap_vld => grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o_ap_vld,
        compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_i => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4,
        compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o => grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o,
        compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o_ap_vld => grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o_ap_vld,
        compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_i => compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s,
        compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o => grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o,
        compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o_ap_vld => grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o_ap_vld);

    mux_42_32_1_1_U146 : component compute_mux_42_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9,
        din1 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4,
        din2 => compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s,
        din3 => p_ZZ7computeP6ap_intILi64EEPS_ILi32EEbRN3hls6streamI7ap_uintILi32EELi0EEES9_E4REG,
        din4 => empty_23_reg_1593,
        dout => tmp_fu_857_p6);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln60_fu_573_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_ready = ap_const_logic_1)) then 
                    grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_ready = ap_const_logic_1)) then 
                    grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((empty_23_reg_1593 = ap_const_lv2_2) and (phase_read_read_fu_376_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s <= self_sum_V_loc_fu_240;
            elsif (((grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s <= grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o;
            end if; 
        end if;
    end process;

    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((empty_23_reg_1593 = ap_const_lv2_1) and (phase_read_read_fu_376_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4 <= self_sum_V_loc_fu_240;
            elsif (((grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4 <= grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o;
            end if; 
        end if;
    end process;

    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((empty_23_reg_1593 = ap_const_lv2_0) and (phase_read_read_fu_376_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9 <= self_sum_V_loc_fu_240;
            elsif (((grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9 <= grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o;
            end if; 
        end if;
    end process;

    dummy_fu_372_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                dummy_fu_372 <= ap_sig_allocacmp_dummy_1;
            end if;
        end if;
    end process;

    i_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_fu_104 <= ap_const_lv3_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                i_fu_104 <= add_ln60_fu_888_p2;
            end if; 
        end if;
    end process;

    indvars_iv1_fu_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvars_iv1_fu_236 <= ap_const_lv2_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                indvars_iv1_fu_236 <= add_ln60_1_reg_1492;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                REG_V_10_fu_148 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_42_out;
                REG_V_11_fu_152 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_43_out;
                REG_V_12_fu_156 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_44_out;
                REG_V_13_fu_160 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_45_out;
                REG_V_14_fu_164 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_46_out;
                REG_V_15_fu_168 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_47_out;
                REG_V_16_fu_172 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_48_out;
                REG_V_17_fu_176 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_49_out;
                REG_V_18_fu_180 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_50_out;
                REG_V_19_fu_184 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_51_out;
                REG_V_1_fu_112 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_33_out;
                REG_V_20_fu_188 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_52_out;
                REG_V_21_fu_192 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_53_out;
                REG_V_22_fu_196 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_54_out;
                REG_V_23_fu_200 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_55_out;
                REG_V_24_fu_204 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_56_out;
                REG_V_25_fu_208 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_57_out;
                REG_V_26_fu_212 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_58_out;
                REG_V_27_fu_216 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_59_out;
                REG_V_28_fu_220 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_60_out;
                REG_V_29_fu_224 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_61_out;
                REG_V_2_fu_116 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_34_out;
                REG_V_30_fu_228 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_62_out;
                REG_V_31_fu_232 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_63_out;
                REG_V_3_fu_120 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_35_out;
                REG_V_4_fu_124 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_36_out;
                REG_V_5_fu_128 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_37_out;
                REG_V_6_fu_132 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_38_out;
                REG_V_7_fu_136 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_39_out;
                REG_V_8_fu_140 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_40_out;
                REG_V_9_fu_144 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_41_out;
                REG_V_fu_108 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_REG_V_32_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln60_1_reg_1492 <= add_ln60_1_fu_579_p2;
                i_1_reg_1478 <= i_fu_104;
                indvars_iv1_load_reg_1484 <= indvars_iv1_fu_236;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln60_fu_573_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                empty_23_reg_1593 <= empty_23_fu_713_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((empty_23_reg_1593 = ap_const_lv2_3) and (phase_read_read_fu_376_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_ZZ7computeP6ap_intILi64EEPS_ILi32EEbRN3hls6streamI7ap_uintILi32EELi0EEES9_E4REG <= self_sum_V_loc_fu_240;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_self_sum_V_out_ap_vld = ap_const_logic_1))) then
                self_sum_V_loc_fu_240 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_self_sum_V_out;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln60_fu_573_p2, grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_done, grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln60_fu_573_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln60_1_fu_579_p2 <= std_logic_vector(unsigned(indvars_iv1_fu_236) + unsigned(ap_const_lv2_1));
    add_ln60_fu_888_p2 <= std_logic_vector(unsigned(i_fu_104) + unsigned(ap_const_lv3_1));
    add_ln77_fu_870_p2 <= std_logic_vector(unsigned(tmp_fu_857_p6) + unsigned(self_sum_V_loc_fu_240));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_done)
    begin
        if ((grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_done)
    begin
        if ((grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln60_fu_573_p2)
    begin
        if (((icmp_ln60_fu_573_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln60_fu_573_p2)
    begin
        if (((icmp_ln60_fu_573_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_dummy_1_assign_proc : process(ap_CS_fsm_state1, dummy_fu_372)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            ap_sig_allocacmp_dummy_1 <= ap_const_lv1_0;
        else 
            ap_sig_allocacmp_dummy_1 <= dummy_fu_372;
        end if; 
    end process;

    buffer_1_address0 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_buffer_1_address0;
    buffer_1_ce0 <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_buffer_1_ce0;

    buffer_2_address0_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_buffer_2_address0, ap_CS_fsm_state6, zext_ln77_fu_883_p1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buffer_2_address0 <= zext_ln77_fu_883_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            buffer_2_address0 <= grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_buffer_2_address0;
        else 
            buffer_2_address0 <= "XXXX";
        end if; 
    end process;


    buffer_2_ce0_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_buffer_2_ce0, ap_CS_fsm_state6, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buffer_2_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            buffer_2_ce0 <= grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_buffer_2_ce0;
        else 
            buffer_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buffer_2_d0_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_buffer_2_d0, ap_CS_fsm_state6, ap_CS_fsm_state4, add_ln77_fu_870_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buffer_2_d0 <= add_ln77_fu_870_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            buffer_2_d0 <= grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_buffer_2_d0;
        else 
            buffer_2_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    buffer_2_we0_assign_proc : process(phase_read_read_fu_376_p2, grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_buffer_2_we0, ap_CS_fsm_state6, ap_CS_fsm_state4)
    begin
        if (((phase_read_read_fu_376_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            buffer_2_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            buffer_2_we0 <= grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_buffer_2_we0;
        else 
            buffer_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    empty_23_fu_713_p1 <= i_fu_104(2 - 1 downto 0);
    fwd_out1_din <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_fwd_out1_din;

    fwd_out1_write_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_fwd_out1_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            fwd_out1_write <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_fwd_out1_write;
        else 
            fwd_out1_write <= ap_const_logic_0;
        end if; 
    end process;

    fwd_out2_din <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_fwd_out2_din;

    fwd_out2_write_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_fwd_out2_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            fwd_out2_write <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_fwd_out2_write;
        else 
            fwd_out2_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_start <= grp_compute_Pipeline_VITIS_LOOP_62_2_fu_395_ap_start_reg;
    grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_start <= grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_ap_start_reg;
    grp_compute_Pipeline_VITIS_LOOP_81_3_fu_471_phase <= (0=>phase, others=>'-');
    icmp_ln60_fu_573_p2 <= "1" when (i_fu_104 = ap_const_lv3_4) else "0";
    lshr_ln_fu_877_p3 <= (empty_23_reg_1593 & empty_23_reg_1593);
    phase_read_read_fu_376_p2 <= (0=>phase, others=>'-');
    zext_ln77_fu_883_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_877_p3),64));
end behav;
