-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity compute_compute_Pipeline_VITIS_LOOP_81_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    i : IN STD_LOGIC_VECTOR (2 downto 0);
    buffer_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    buffer_2_ce0 : OUT STD_LOGIC;
    buffer_2_we0 : OUT STD_LOGIC;
    buffer_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    REG_V_32_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_40_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_48_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_56_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    indvars_iv1 : IN STD_LOGIC_VECTOR (1 downto 0);
    REG_V_36_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_44_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_52_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_60_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_33_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_41_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_49_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_57_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_37_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_45_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_53_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_61_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_34_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_42_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_50_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_58_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_38_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_46_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_54_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_62_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_35_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_43_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_51_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_59_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_39_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_47_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_55_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    REG_V_63_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    i_cast : IN STD_LOGIC_VECTOR (1 downto 0);
    zext_ln60 : IN STD_LOGIC_VECTOR (2 downto 0);
    phase : IN STD_LOGIC_VECTOR (0 downto 0);
    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_i : IN STD_LOGIC_VECTOR (31 downto 0);
    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o_ap_vld : OUT STD_LOGIC;
    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_i : IN STD_LOGIC_VECTOR (31 downto 0);
    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o_ap_vld : OUT STD_LOGIC;
    compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_i : IN STD_LOGIC_VECTOR (31 downto 0);
    compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of compute_compute_Pipeline_VITIS_LOOP_81_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln81_reg_1245 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal phase_read_reg_1095 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln60_cast_fu_429_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln60_cast_reg_1229 : STD_LOGIC_VECTOR (3 downto 0);
    signal com_1_reg_1234 : STD_LOGIC_VECTOR (1 downto 0);
    signal com_1_reg_1234_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal com_1_reg_1234_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln81_fu_445_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln81_reg_1245_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_598_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_reg_1289 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal grp_fu_1029_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1035_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1041_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1047_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1494_7_reg_1349 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1494_7_reg_1349_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln89_3_fu_697_p2 : STD_LOGIC_VECTOR (31 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln89_3_fu_697_p2 : signal is "no";
    signal add_ln89_3_reg_1355 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1062_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln840_reg_1360 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1_fu_701_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln1_reg_1365 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln93_1_fu_801_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln93_1_reg_1371 : STD_LOGIC_VECTOR (3 downto 0);
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_load_reg_1376 : STD_LOGIC_VECTOR (31 downto 0);
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_8_load_reg_1381 : STD_LOGIC_VECTOR (31 downto 0);
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_7_load_reg_1386 : STD_LOGIC_VECTOR (31 downto 0);
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_6_load_reg_1391 : STD_LOGIC_VECTOR (31 downto 0);
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_5_load_reg_1396 : STD_LOGIC_VECTOR (31 downto 0);
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_load_reg_1401 : STD_LOGIC_VECTOR (31 downto 0);
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_3_load_reg_1406 : STD_LOGIC_VECTOR (31 downto 0);
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_2_load_reg_1411 : STD_LOGIC_VECTOR (31 downto 0);
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_1_load_reg_1416 : STD_LOGIC_VECTOR (31 downto 0);
    signal compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_load_reg_1421 : STD_LOGIC_VECTOR (31 downto 0);
    signal compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_reg_1426 : STD_LOGIC_VECTOR (31 downto 0);
    signal compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_18_reg_1431 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln93_fu_797_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln92_fu_920_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal add_ln186_fu_925_p2 : STD_LOGIC_VECTOR (31 downto 0);
    attribute use_dsp48 of add_ln186_fu_925_p2 : signal is "no";
    signal com_fu_182 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln81_fu_451_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_com_1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln89_fu_902_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln90_fu_1023_p2 : STD_LOGIC_VECTOR (31 downto 0);
    attribute use_dsp48 of add_ln90_fu_1023_p2 : signal is "no";
    signal com_cast_fu_441_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_457_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_475_p5 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_1_fu_491_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_1_fu_509_p5 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_1_fu_525_p5 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_11_1_fu_541_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_3_fu_559_p5 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_11_3_fu_575_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_2_fu_607_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_2_fu_620_p5 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_2_fu_632_p5 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_11_2_fu_644_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_3_fu_657_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_3_fu_670_p5 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_682_p5 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1070_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1053_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_867_p17 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln_fu_908_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln93_fu_915_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_1079_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_1001_p14 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln90_1_fu_1018_p2 : STD_LOGIC_VECTOR (31 downto 0);
    attribute use_dsp48 of add_ln90_1_fu_1018_p2 : signal is "no";
    signal grp_fu_1029_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1029_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1035_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1035_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1041_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1041_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1047_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1047_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1053_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1053_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1062_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1062_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1070_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1070_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1079_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1079_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to3 : STD_LOGIC;
    signal ap_done_pending_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_1029_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1029_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1035_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1035_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1041_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1041_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1047_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1047_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1053_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1053_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1062_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1062_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1070_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1070_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1079_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_1079_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_855 : BOOLEAN;
    signal ap_condition_859 : BOOLEAN;
    signal ap_condition_862 : BOOLEAN;
    signal ap_condition_867 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component compute_mux_42_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component compute_mux_32_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component compute_mux_154_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component compute_mux_124_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component compute_mul_mul_16ns_16ns_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component compute_mac_muladd_16ns_16ns_32ns_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component compute_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_42_16_1_1_U74 : component compute_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG_V_32_reload,
        din1 => REG_V_40_reload,
        din2 => REG_V_48_reload,
        din3 => REG_V_56_reload,
        din4 => indvars_iv1,
        dout => tmp_7_fu_457_p6);

    mux_32_16_1_1_U75 : component compute_mux_32_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG_V_36_reload,
        din1 => REG_V_44_reload,
        din2 => REG_V_52_reload,
        din3 => ap_sig_allocacmp_com_1,
        dout => tmp_1_fu_475_p5);

    mux_42_16_1_1_U76 : component compute_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG_V_33_reload,
        din1 => REG_V_41_reload,
        din2 => REG_V_49_reload,
        din3 => REG_V_57_reload,
        din4 => indvars_iv1,
        dout => tmp_7_1_fu_491_p6);

    mux_32_16_1_1_U77 : component compute_mux_32_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG_V_37_reload,
        din1 => REG_V_45_reload,
        din2 => REG_V_53_reload,
        din3 => ap_sig_allocacmp_com_1,
        dout => tmp_1_1_fu_509_p5);

    mux_32_16_1_1_U78 : component compute_mux_32_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG_V_33_reload,
        din1 => REG_V_41_reload,
        din2 => REG_V_49_reload,
        din3 => ap_sig_allocacmp_com_1,
        dout => tmp_2_1_fu_525_p5);

    mux_42_16_1_1_U79 : component compute_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG_V_37_reload,
        din1 => REG_V_45_reload,
        din2 => REG_V_53_reload,
        din3 => REG_V_61_reload,
        din4 => indvars_iv1,
        dout => tmp_11_1_fu_541_p6);

    mux_32_16_1_1_U80 : component compute_mux_32_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG_V_35_reload,
        din1 => REG_V_43_reload,
        din2 => REG_V_51_reload,
        din3 => ap_sig_allocacmp_com_1,
        dout => tmp_2_3_fu_559_p5);

    mux_42_16_1_1_U81 : component compute_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG_V_39_reload,
        din1 => REG_V_47_reload,
        din2 => REG_V_55_reload,
        din3 => REG_V_63_reload,
        din4 => indvars_iv1,
        dout => tmp_11_3_fu_575_p6);

    mux_42_16_1_1_U82 : component compute_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG_V_36_reload,
        din1 => REG_V_44_reload,
        din2 => REG_V_52_reload,
        din3 => REG_V_60_reload,
        din4 => indvars_iv1,
        dout => tmp_4_fu_598_p6);

    mux_42_16_1_1_U83 : component compute_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG_V_34_reload,
        din1 => REG_V_42_reload,
        din2 => REG_V_50_reload,
        din3 => REG_V_58_reload,
        din4 => indvars_iv1,
        dout => tmp_7_2_fu_607_p6);

    mux_32_16_1_1_U84 : component compute_mux_32_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG_V_38_reload,
        din1 => REG_V_46_reload,
        din2 => REG_V_54_reload,
        din3 => com_1_reg_1234,
        dout => tmp_1_2_fu_620_p5);

    mux_32_16_1_1_U85 : component compute_mux_32_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG_V_34_reload,
        din1 => REG_V_42_reload,
        din2 => REG_V_50_reload,
        din3 => com_1_reg_1234,
        dout => tmp_2_2_fu_632_p5);

    mux_42_16_1_1_U86 : component compute_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG_V_38_reload,
        din1 => REG_V_46_reload,
        din2 => REG_V_54_reload,
        din3 => REG_V_62_reload,
        din4 => indvars_iv1,
        dout => tmp_11_2_fu_644_p6);

    mux_42_16_1_1_U87 : component compute_mux_42_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG_V_35_reload,
        din1 => REG_V_43_reload,
        din2 => REG_V_51_reload,
        din3 => REG_V_59_reload,
        din4 => indvars_iv1,
        dout => tmp_7_3_fu_657_p6);

    mux_32_16_1_1_U88 : component compute_mux_32_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG_V_39_reload,
        din1 => REG_V_47_reload,
        din2 => REG_V_55_reload,
        din3 => com_1_reg_1234,
        dout => tmp_1_3_fu_670_p5);

    mux_32_16_1_1_U89 : component compute_mux_32_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => REG_V_32_reload,
        din1 => REG_V_40_reload,
        din2 => REG_V_48_reload,
        din3 => com_1_reg_1234_pp0_iter1_reg,
        dout => tmp_2_fu_682_p5);

    mux_154_32_1_1_U90 : component compute_mux_154_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 32,
        din9_WIDTH => 32,
        din10_WIDTH => 32,
        din11_WIDTH => 32,
        din12_WIDTH => 32,
        din13_WIDTH => 32,
        din14_WIDTH => 32,
        din15_WIDTH => 4,
        dout_WIDTH => 32)
    port map (
        din0 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_i,
        din1 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_8,
        din2 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_7,
        din3 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_6,
        din4 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_5,
        din5 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_i,
        din6 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_3,
        din7 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_2,
        din8 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_1,
        din9 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1,
        din10 => compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_i,
        din11 => compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_0,
        din12 => compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_1,
        din13 => compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_2,
        din14 => compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_3,
        din15 => add_ln1_reg_1365,
        dout => tmp_s_fu_867_p17);

    mux_124_32_1_1_U91 : component compute_mux_124_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 32,
        din9_WIDTH => 32,
        din10_WIDTH => 32,
        din11_WIDTH => 32,
        din12_WIDTH => 4,
        dout_WIDTH => 32)
    port map (
        din0 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_load_reg_1376,
        din1 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_8_load_reg_1381,
        din2 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_7_load_reg_1386,
        din3 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_6_load_reg_1391,
        din4 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_5_load_reg_1396,
        din5 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_load_reg_1401,
        din6 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_3_load_reg_1406,
        din7 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_2_load_reg_1411,
        din8 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_1_load_reg_1416,
        din9 => compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_load_reg_1421,
        din10 => compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_reg_1426,
        din11 => compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_18_reg_1431,
        din12 => add_ln93_1_reg_1371,
        dout => tmp_3_fu_1001_p14);

    mul_mul_16ns_16ns_32_4_1_U92 : component compute_mul_mul_16ns_16ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1029_p0,
        din1 => grp_fu_1029_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_1029_p2);

    mul_mul_16ns_16ns_32_4_1_U93 : component compute_mul_mul_16ns_16ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1035_p0,
        din1 => grp_fu_1035_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_1035_p2);

    mul_mul_16ns_16ns_32_4_1_U94 : component compute_mul_mul_16ns_16ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1041_p0,
        din1 => grp_fu_1041_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_1041_p2);

    mul_mul_16ns_16ns_32_4_1_U95 : component compute_mul_mul_16ns_16ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1047_p0,
        din1 => grp_fu_1047_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_1047_p2);

    mac_muladd_16ns_16ns_32ns_32_4_1_U96 : component compute_mac_muladd_16ns_16ns_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1053_p0,
        din1 => grp_fu_1053_p1,
        din2 => grp_fu_1029_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1053_p3);

    mac_muladd_16ns_16ns_32ns_32_4_1_U97 : component compute_mac_muladd_16ns_16ns_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1062_p0,
        din1 => grp_fu_1062_p1,
        din2 => grp_fu_1041_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1062_p3);

    mac_muladd_16ns_16ns_32ns_32_4_1_U98 : component compute_mac_muladd_16ns_16ns_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1070_p0,
        din1 => grp_fu_1070_p1,
        din2 => grp_fu_1035_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1070_p3);

    mac_muladd_16ns_16ns_32ns_32_4_1_U99 : component compute_mac_muladd_16ns_16ns_32ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1079_p0,
        din1 => grp_fu_1079_p1,
        din2 => add_ln840_reg_1360,
        ce => ap_const_logic_1,
        dout => grp_fu_1079_p3);

    flow_control_loop_pipe_sequential_init_U : component compute_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    com_fu_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln81_fu_445_p2 = ap_const_lv1_0))) then 
                    com_fu_182 <= add_ln81_fu_451_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    com_fu_182 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_0_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_const_boolean_1 = ap_condition_859)) then 
                    compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_0 <= add_ln89_3_fu_697_p2;
                elsif ((ap_const_boolean_1 = ap_condition_855)) then 
                    compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_0 <= add_ln186_fu_925_p2;
                end if;
            end if; 
        end if;
    end process;

    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_867)) then
                if (((ap_const_lv4_9 = add_ln1_fu_701_p3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1 <= add_ln89_3_fu_697_p2;
                elsif (((ap_const_lv4_9 = add_ln93_1_reg_1371) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1 <= add_ln186_fu_925_p2;
                end if;
            end if; 
        end if;
    end process;

    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_867)) then
                if (((ap_const_lv4_8 = add_ln1_fu_701_p3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_1 <= add_ln89_3_fu_697_p2;
                elsif (((ap_const_lv4_8 = add_ln93_1_reg_1371) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_1 <= add_ln186_fu_925_p2;
                end if;
            end if; 
        end if;
    end process;

    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_867)) then
                if (((ap_const_lv4_7 = add_ln1_fu_701_p3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_2 <= add_ln89_3_fu_697_p2;
                elsif (((ap_const_lv4_7 = add_ln93_1_reg_1371) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_2 <= add_ln186_fu_925_p2;
                end if;
            end if; 
        end if;
    end process;

    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_867)) then
                if (((ap_const_lv4_6 = add_ln1_fu_701_p3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_3 <= add_ln89_3_fu_697_p2;
                elsif (((ap_const_lv4_6 = add_ln93_1_reg_1371) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_3 <= add_ln186_fu_925_p2;
                end if;
            end if; 
        end if;
    end process;

    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_5_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_867)) then
                if (((ap_const_lv4_4 = add_ln1_fu_701_p3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_5 <= add_ln89_3_fu_697_p2;
                elsif (((ap_const_lv4_4 = add_ln93_1_reg_1371) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_5 <= add_ln186_fu_925_p2;
                end if;
            end if; 
        end if;
    end process;

    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_6_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_867)) then
                if (((ap_const_lv4_3 = add_ln1_fu_701_p3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_6 <= add_ln89_3_fu_697_p2;
                elsif (((ap_const_lv4_3 = add_ln93_1_reg_1371) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_6 <= add_ln186_fu_925_p2;
                end if;
            end if; 
        end if;
    end process;

    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_7_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_867)) then
                if (((ap_const_lv4_2 = add_ln1_fu_701_p3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_7 <= add_ln89_3_fu_697_p2;
                elsif (((ap_const_lv4_2 = add_ln93_1_reg_1371) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_7 <= add_ln186_fu_925_p2;
                end if;
            end if; 
        end if;
    end process;

    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_8_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_867)) then
                if (((ap_const_lv4_1 = add_ln1_fu_701_p3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_8 <= add_ln89_3_fu_697_p2;
                elsif (((ap_const_lv4_1 = add_ln93_1_reg_1371) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_8 <= add_ln186_fu_925_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln1_reg_1365 <= add_ln1_fu_701_p3;
                add_ln89_3_reg_1355 <= add_ln89_3_fu_697_p2;
                com_1_reg_1234 <= ap_sig_allocacmp_com_1;
                com_1_reg_1234_pp0_iter1_reg <= com_1_reg_1234;
                com_1_reg_1234_pp0_iter2_reg <= com_1_reg_1234_pp0_iter1_reg;
                icmp_ln81_reg_1245 <= icmp_ln81_fu_445_p2;
                icmp_ln81_reg_1245_pp0_iter1_reg <= icmp_ln81_reg_1245;
                    zext_ln60_cast_reg_1229(2 downto 0) <= zext_ln60_cast_fu_429_p1(2 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln840_reg_1360 <= grp_fu_1062_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln93_1_reg_1371 <= add_ln93_1_fu_801_p3;
                mul_ln1494_7_reg_1349 <= grp_fu_1047_p2;
                mul_ln1494_7_reg_1349_pp0_iter2_reg <= mul_ln1494_7_reg_1349;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv4_C = add_ln1_fu_701_p3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_read_reg_1095 = ap_const_lv1_0))) then
                compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_1 <= add_ln89_3_fu_697_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (phase_read_reg_1095 = ap_const_lv1_1))) then
                compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_18_reg_1431 <= compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_0;
                compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_reg_1426 <= compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_i;
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_1_load_reg_1416 <= compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_1;
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_2_load_reg_1411 <= compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_2;
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_3_load_reg_1406 <= compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_3;
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_load_reg_1401 <= compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_i;
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_5_load_reg_1396 <= compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_5;
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_6_load_reg_1391 <= compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_6;
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_7_load_reg_1386 <= compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_7;
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_8_load_reg_1381 <= compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_8;
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_load_reg_1376 <= compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_i;
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_load_reg_1421 <= compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv4_D = add_ln1_fu_701_p3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_read_reg_1095 = ap_const_lv1_0))) then
                compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_2 <= add_ln89_3_fu_697_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((ap_const_lv4_E = add_ln1_fu_701_p3) and (phase_read_reg_1095 = ap_const_lv1_0)) or ((ap_const_lv4_F = add_ln1_fu_701_p3) and (phase_read_reg_1095 = ap_const_lv1_0))))) then
                compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_3 <= add_ln89_3_fu_697_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln81_reg_1245 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                tmp_4_reg_1289 <= tmp_4_fu_598_p6;
            end if;
        end if;
    end process;
    zext_ln60_cast_reg_1229(3) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter2_stage0, ap_idle_pp0_0to1, ap_idle_pp0_1to3, ap_done_pending_pp0, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to1 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_done_pending_pp0 = ap_const_logic_0) and (ap_idle_pp0_1to3 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln186_fu_925_p2 <= std_logic_vector(unsigned(mul_ln1494_7_reg_1349_pp0_iter2_reg) + unsigned(grp_fu_1079_p3));
    add_ln1_fu_701_p3 <= (i_cast & com_1_reg_1234_pp0_iter1_reg);
    add_ln81_fu_451_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_com_1) + unsigned(ap_const_lv2_1));
    add_ln89_3_fu_697_p2 <= std_logic_vector(unsigned(grp_fu_1070_p3) + unsigned(grp_fu_1053_p3));
    add_ln89_fu_902_p2 <= std_logic_vector(unsigned(tmp_s_fu_867_p17) + unsigned(add_ln89_3_reg_1355));
    add_ln90_1_fu_1018_p2 <= std_logic_vector(unsigned(grp_fu_1079_p3) + unsigned(tmp_3_fu_1001_p14));
    add_ln90_fu_1023_p2 <= std_logic_vector(unsigned(add_ln90_1_fu_1018_p2) + unsigned(mul_ln1494_7_reg_1349_pp0_iter2_reg));
    add_ln93_1_fu_801_p3 <= (com_1_reg_1234_pp0_iter2_reg & i_cast);
    add_ln93_fu_915_p2 <= std_logic_vector(unsigned(shl_ln_fu_908_p3) + unsigned(zext_ln60_cast_reg_1229));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_855_assign_proc : process(ap_enable_reg_pp0_iter3, phase_read_reg_1095, add_ln93_1_reg_1371)
    begin
                ap_condition_855 <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and ((((((ap_const_lv4_E = add_ln93_1_reg_1371) and (phase_read_reg_1095 = ap_const_lv1_0)) or ((ap_const_lv4_F = add_ln93_1_reg_1371) and (phase_read_reg_1095 = ap_const_lv1_0))) or ((ap_const_lv4_D = add_ln93_1_reg_1371) and (phase_read_reg_1095 = ap_const_lv1_0))) or ((ap_const_lv4_C = add_ln93_1_reg_1371) and (phase_read_reg_1095 = ap_const_lv1_0))) or ((ap_const_lv4_B = add_ln93_1_reg_1371) and (phase_read_reg_1095 = ap_const_lv1_0))));
    end process;


    ap_condition_859_assign_proc : process(ap_enable_reg_pp0_iter2, phase_read_reg_1095, add_ln1_fu_701_p3)
    begin
                ap_condition_859 <= ((ap_const_lv4_B = add_ln1_fu_701_p3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (phase_read_reg_1095 = ap_const_lv1_0));
    end process;


    ap_condition_862_assign_proc : process(ap_CS_fsm_pp0_stage0, phase_read_reg_1095, ap_block_pp0_stage0)
    begin
                ap_condition_862 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_read_reg_1095 = ap_const_lv1_0));
    end process;


    ap_condition_867_assign_proc : process(ap_CS_fsm_pp0_stage0, phase_read_reg_1095, ap_block_pp0_stage0_11001)
    begin
                ap_condition_867 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_read_reg_1095 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln81_reg_1245)
    begin
        if (((icmp_ln81_reg_1245 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln81_reg_1245_pp0_iter1_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln81_reg_1245_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_done_pending_pp0_assign_proc : process(ap_loop_exit_ready, ap_loop_exit_ready_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (not(((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0) and (ap_loop_exit_ready = ap_const_logic_0)))) then 
            ap_done_pending_pp0 <= ap_const_logic_1;
        else 
            ap_done_pending_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to3_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to3 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_com_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, com_fu_182, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_com_1 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_com_1 <= com_fu_182;
        end if; 
    end process;


    buffer_2_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, zext_ln93_fu_797_p1, ap_block_pp0_stage1, zext_ln92_fu_920_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_2_address0 <= zext_ln92_fu_920_p1(4 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buffer_2_address0 <= zext_ln93_fu_797_p1(4 - 1 downto 0);
        else 
            buffer_2_address0 <= "XXXX";
        end if; 
    end process;


    buffer_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buffer_2_ce0 <= ap_const_logic_1;
        else 
            buffer_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buffer_2_d0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_block_pp0_stage0, add_ln89_fu_902_p2, add_ln90_fu_1023_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buffer_2_d0 <= add_ln90_fu_1023_p2;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            buffer_2_d0 <= add_ln89_fu_902_p2;
        else 
            buffer_2_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    buffer_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, phase_read_reg_1095, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (phase_read_reg_1095 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_read_reg_1095 = ap_const_lv1_1)))) then 
            buffer_2_we0 <= ap_const_logic_1;
        else 
            buffer_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    com_cast_fu_441_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_com_1),3));

    compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_i, add_ln89_3_fu_697_p2, add_ln1_fu_701_p3, add_ln93_1_reg_1371, add_ln186_fu_925_p2, ap_condition_862)
    begin
        if ((ap_const_boolean_1 = ap_condition_862)) then
            if (((ap_const_lv4_A = add_ln1_fu_701_p3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o <= add_ln89_3_fu_697_p2;
            elsif (((ap_const_lv4_A = add_ln93_1_reg_1371) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o <= add_ln186_fu_925_p2;
            else 
                compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o <= compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_i;
            end if;
        else 
            compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o <= compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_i;
        end if; 
    end process;


    compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, phase_read_reg_1095, ap_block_pp0_stage0_11001, add_ln1_fu_701_p3, add_ln93_1_reg_1371)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv4_A = add_ln1_fu_701_p3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_read_reg_1095 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv4_A = add_ln93_1_reg_1371) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_read_reg_1095 = ap_const_lv1_0)))) then 
            compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o_ap_vld <= ap_const_logic_1;
        else 
            compute_ap_int_64_ap_int_32_bool_hls_stream_ap_uint_32_0_hls_stream_ap_uint_32_0_REG_s_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_i, add_ln89_3_fu_697_p2, add_ln1_fu_701_p3, add_ln93_1_reg_1371, add_ln186_fu_925_p2, ap_condition_862)
    begin
        if ((ap_const_boolean_1 = ap_condition_862)) then
            if (((ap_const_lv4_5 = add_ln1_fu_701_p3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o <= add_ln89_3_fu_697_p2;
            elsif (((ap_const_lv4_5 = add_ln93_1_reg_1371) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o <= add_ln186_fu_925_p2;
            else 
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o <= compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_i;
            end if;
        else 
            compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o <= compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_i;
        end if; 
    end process;


    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, phase_read_reg_1095, ap_block_pp0_stage0_11001, add_ln1_fu_701_p3, add_ln93_1_reg_1371)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv4_5 = add_ln1_fu_701_p3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_read_reg_1095 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv4_5 = add_ln93_1_reg_1371) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_read_reg_1095 = ap_const_lv1_0)))) then 
            compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o_ap_vld <= ap_const_logic_1;
        else 
            compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_4_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_i, add_ln89_3_fu_697_p2, add_ln1_fu_701_p3, add_ln93_1_reg_1371, add_ln186_fu_925_p2, ap_condition_862)
    begin
        if ((ap_const_boolean_1 = ap_condition_862)) then
            if (((ap_const_lv4_0 = add_ln1_fu_701_p3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o <= add_ln89_3_fu_697_p2;
            elsif (((ap_const_lv4_0 = add_ln93_1_reg_1371) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o <= add_ln186_fu_925_p2;
            else 
                compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o <= compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_i;
            end if;
        else 
            compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o <= compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_i;
        end if; 
    end process;


    compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, phase_read_reg_1095, ap_block_pp0_stage0_11001, add_ln1_fu_701_p3, add_ln93_1_reg_1371)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv4_0 = add_ln1_fu_701_p3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_read_reg_1095 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv4_0 = add_ln93_1_reg_1371) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (phase_read_reg_1095 = ap_const_lv1_0)))) then 
            compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o_ap_vld <= ap_const_logic_1;
        else 
            compute_ap_int_ap_int_bool_stream_stream_ap_uint_32_0_REG1_9_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1029_p0 <= grp_fu_1029_p00(16 - 1 downto 0);
    grp_fu_1029_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_475_p5),32));
    grp_fu_1029_p1 <= grp_fu_1029_p10(16 - 1 downto 0);
    grp_fu_1029_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_457_p6),32));
    grp_fu_1035_p0 <= grp_fu_1035_p00(16 - 1 downto 0);
    grp_fu_1035_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_1_fu_509_p5),32));
    grp_fu_1035_p1 <= grp_fu_1035_p10(16 - 1 downto 0);
    grp_fu_1035_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_1_fu_491_p6),32));
    grp_fu_1041_p0 <= grp_fu_1041_p00(16 - 1 downto 0);
    grp_fu_1041_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_1_fu_541_p6),32));
    grp_fu_1041_p1 <= grp_fu_1041_p10(16 - 1 downto 0);
    grp_fu_1041_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_1_fu_525_p5),32));
    grp_fu_1047_p0 <= grp_fu_1047_p00(16 - 1 downto 0);
    grp_fu_1047_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_3_fu_575_p6),32));
    grp_fu_1047_p1 <= grp_fu_1047_p10(16 - 1 downto 0);
    grp_fu_1047_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_3_fu_559_p5),32));
    grp_fu_1053_p0 <= grp_fu_1053_p00(16 - 1 downto 0);
    grp_fu_1053_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_2_fu_620_p5),32));
    grp_fu_1053_p1 <= grp_fu_1053_p10(16 - 1 downto 0);
    grp_fu_1053_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_2_fu_607_p6),32));
    grp_fu_1062_p0 <= grp_fu_1062_p00(16 - 1 downto 0);
    grp_fu_1062_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_2_fu_644_p6),32));
    grp_fu_1062_p1 <= grp_fu_1062_p10(16 - 1 downto 0);
    grp_fu_1062_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_2_fu_632_p5),32));
    grp_fu_1070_p0 <= grp_fu_1070_p00(16 - 1 downto 0);
    grp_fu_1070_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_3_fu_670_p5),32));
    grp_fu_1070_p1 <= grp_fu_1070_p10(16 - 1 downto 0);
    grp_fu_1070_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_3_fu_657_p6),32));
    grp_fu_1079_p0 <= grp_fu_1079_p00(16 - 1 downto 0);
    grp_fu_1079_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_reg_1289),32));
    grp_fu_1079_p1 <= grp_fu_1079_p10(16 - 1 downto 0);
    grp_fu_1079_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_682_p5),32));
    icmp_ln81_fu_445_p2 <= "1" when (com_cast_fu_441_p1 = i) else "0";
    phase_read_reg_1095 <= phase;
    shl_ln_fu_908_p3 <= (com_1_reg_1234_pp0_iter2_reg & ap_const_lv2_0);
    zext_ln60_cast_fu_429_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln60),4));
    zext_ln92_fu_920_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln93_fu_915_p2),64));
    zext_ln93_fu_797_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1_reg_1365),64));
end behav;
