// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module compute_compute_Pipeline_VITIS_LOOP_79_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        i,
        REG_V_32_reload,
        REG_V_40_reload,
        REG_V_48_reload,
        REG_V_56_reload,
        indvars_iv1,
        REG_V_36_reload,
        REG_V_44_reload,
        REG_V_52_reload,
        REG_V_60_reload,
        REG_V_33_reload,
        REG_V_41_reload,
        REG_V_49_reload,
        REG_V_57_reload,
        REG_V_37_reload,
        REG_V_45_reload,
        REG_V_53_reload,
        REG_V_61_reload,
        REG_V_34_reload,
        REG_V_42_reload,
        REG_V_50_reload,
        REG_V_58_reload,
        REG_V_38_reload,
        REG_V_46_reload,
        REG_V_54_reload,
        REG_V_62_reload,
        REG_V_35_reload,
        REG_V_43_reload,
        REG_V_51_reload,
        REG_V_59_reload,
        REG_V_39_reload,
        REG_V_47_reload,
        REG_V_55_reload,
        REG_V_63_reload,
        phase,
        i_cast,
        buffer_2_address0,
        buffer_2_ce0,
        buffer_2_we0,
        buffer_2_d0,
        buffer_2_address1,
        buffer_2_ce1,
        buffer_2_we1,
        buffer_2_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [2:0] i;
input  [15:0] REG_V_32_reload;
input  [15:0] REG_V_40_reload;
input  [15:0] REG_V_48_reload;
input  [15:0] REG_V_56_reload;
input  [1:0] indvars_iv1;
input  [15:0] REG_V_36_reload;
input  [15:0] REG_V_44_reload;
input  [15:0] REG_V_52_reload;
input  [15:0] REG_V_60_reload;
input  [15:0] REG_V_33_reload;
input  [15:0] REG_V_41_reload;
input  [15:0] REG_V_49_reload;
input  [15:0] REG_V_57_reload;
input  [15:0] REG_V_37_reload;
input  [15:0] REG_V_45_reload;
input  [15:0] REG_V_53_reload;
input  [15:0] REG_V_61_reload;
input  [15:0] REG_V_34_reload;
input  [15:0] REG_V_42_reload;
input  [15:0] REG_V_50_reload;
input  [15:0] REG_V_58_reload;
input  [15:0] REG_V_38_reload;
input  [15:0] REG_V_46_reload;
input  [15:0] REG_V_54_reload;
input  [15:0] REG_V_62_reload;
input  [15:0] REG_V_35_reload;
input  [15:0] REG_V_43_reload;
input  [15:0] REG_V_51_reload;
input  [15:0] REG_V_59_reload;
input  [15:0] REG_V_39_reload;
input  [15:0] REG_V_47_reload;
input  [15:0] REG_V_55_reload;
input  [15:0] REG_V_63_reload;
input  [0:0] phase;
input  [1:0] i_cast;
output  [3:0] buffer_2_address0;
output   buffer_2_ce0;
output   buffer_2_we0;
output  [31:0] buffer_2_d0;
output  [3:0] buffer_2_address1;
output   buffer_2_ce1;
output   buffer_2_we1;
output  [31:0] buffer_2_d1;

reg ap_idle;
reg buffer_2_ce0;
reg buffer_2_we0;
reg buffer_2_ce1;
reg buffer_2_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln79_fu_375_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] phase_read_reg_733;
reg   [1:0] com_1_reg_837;
reg   [1:0] com_1_reg_837_pp0_iter1_reg;
reg   [1:0] com_1_reg_837_pp0_iter2_reg;
reg   [1:0] com_1_reg_837_pp0_iter3_reg;
wire   [31:0] grp_fu_660_p2;
wire   [31:0] grp_fu_666_p2;
wire   [31:0] grp_fu_672_p2;
wire   [31:0] grp_fu_678_p2;
wire   [63:0] zext_ln87_fu_644_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln88_fu_655_p1;
reg   [1:0] com_fu_118;
wire   [1:0] add_ln79_fu_381_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_com_1;
wire   [2:0] com_cast_fu_371_p1;
wire   [15:0] tmp_4_1_fu_387_p6;
wire   [15:0] tmp_8_1_fu_405_p5;
wire   [15:0] tmp_9_1_fu_421_p5;
wire   [15:0] tmp_10_1_fu_437_p6;
wire   [15:0] tmp_4_2_fu_455_p6;
wire   [15:0] tmp_8_2_fu_473_p5;
wire   [15:0] tmp_9_2_fu_489_p5;
wire   [15:0] tmp_10_2_fu_505_p6;
wire   [15:0] tmp_4_fu_528_p6;
wire   [15:0] tmp_8_fu_541_p5;
wire   [15:0] tmp_9_fu_553_p5;
wire   [15:0] tmp_s_fu_565_p6;
wire   [15:0] tmp_4_3_fu_578_p6;
wire   [15:0] tmp_8_3_fu_591_p5;
wire   [15:0] tmp_9_3_fu_603_p5;
wire   [15:0] tmp_10_3_fu_615_p6;
wire   [31:0] grp_fu_702_p3;
wire   [31:0] grp_fu_684_p3;
wire   [31:0] grp_fu_711_p3;
wire   [31:0] grp_fu_693_p3;
wire   [3:0] add_ln87_3_fu_638_p3;
wire   [3:0] add_ln88_3_fu_649_p3;
wire   [15:0] grp_fu_660_p0;
wire   [15:0] grp_fu_660_p1;
wire   [15:0] grp_fu_666_p0;
wire   [15:0] grp_fu_666_p1;
wire   [15:0] grp_fu_672_p0;
wire   [15:0] grp_fu_672_p1;
wire   [15:0] grp_fu_678_p0;
wire   [15:0] grp_fu_678_p1;
wire   [15:0] grp_fu_684_p0;
wire   [15:0] grp_fu_684_p1;
wire   [15:0] grp_fu_693_p0;
wire   [15:0] grp_fu_693_p1;
wire   [15:0] grp_fu_702_p0;
wire   [15:0] grp_fu_702_p1;
wire   [15:0] grp_fu_711_p0;
wire   [15:0] grp_fu_711_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [31:0] grp_fu_660_p00;
wire   [31:0] grp_fu_660_p10;
wire   [31:0] grp_fu_666_p00;
wire   [31:0] grp_fu_666_p10;
wire   [31:0] grp_fu_672_p00;
wire   [31:0] grp_fu_672_p10;
wire   [31:0] grp_fu_678_p00;
wire   [31:0] grp_fu_678_p10;
wire   [31:0] grp_fu_684_p00;
wire   [31:0] grp_fu_684_p10;
wire   [31:0] grp_fu_693_p00;
wire   [31:0] grp_fu_693_p10;
wire   [31:0] grp_fu_702_p00;
wire   [31:0] grp_fu_702_p10;
wire   [31:0] grp_fu_711_p00;
wire   [31:0] grp_fu_711_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

compute_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U74(
    .din0(REG_V_33_reload),
    .din1(REG_V_41_reload),
    .din2(REG_V_49_reload),
    .din3(REG_V_57_reload),
    .din4(indvars_iv1),
    .dout(tmp_4_1_fu_387_p6)
);

compute_mux_32_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_32_16_1_1_U75(
    .din0(REG_V_37_reload),
    .din1(REG_V_45_reload),
    .din2(REG_V_53_reload),
    .din3(ap_sig_allocacmp_com_1),
    .dout(tmp_8_1_fu_405_p5)
);

compute_mux_32_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_32_16_1_1_U76(
    .din0(REG_V_33_reload),
    .din1(REG_V_41_reload),
    .din2(REG_V_49_reload),
    .din3(ap_sig_allocacmp_com_1),
    .dout(tmp_9_1_fu_421_p5)
);

compute_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U77(
    .din0(REG_V_37_reload),
    .din1(REG_V_45_reload),
    .din2(REG_V_53_reload),
    .din3(REG_V_61_reload),
    .din4(indvars_iv1),
    .dout(tmp_10_1_fu_437_p6)
);

compute_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U78(
    .din0(REG_V_34_reload),
    .din1(REG_V_42_reload),
    .din2(REG_V_50_reload),
    .din3(REG_V_58_reload),
    .din4(indvars_iv1),
    .dout(tmp_4_2_fu_455_p6)
);

compute_mux_32_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_32_16_1_1_U79(
    .din0(REG_V_38_reload),
    .din1(REG_V_46_reload),
    .din2(REG_V_54_reload),
    .din3(ap_sig_allocacmp_com_1),
    .dout(tmp_8_2_fu_473_p5)
);

compute_mux_32_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_32_16_1_1_U80(
    .din0(REG_V_34_reload),
    .din1(REG_V_42_reload),
    .din2(REG_V_50_reload),
    .din3(ap_sig_allocacmp_com_1),
    .dout(tmp_9_2_fu_489_p5)
);

compute_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U81(
    .din0(REG_V_38_reload),
    .din1(REG_V_46_reload),
    .din2(REG_V_54_reload),
    .din3(REG_V_62_reload),
    .din4(indvars_iv1),
    .dout(tmp_10_2_fu_505_p6)
);

compute_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U82(
    .din0(REG_V_32_reload),
    .din1(REG_V_40_reload),
    .din2(REG_V_48_reload),
    .din3(REG_V_56_reload),
    .din4(indvars_iv1),
    .dout(tmp_4_fu_528_p6)
);

compute_mux_32_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_32_16_1_1_U83(
    .din0(REG_V_36_reload),
    .din1(REG_V_44_reload),
    .din2(REG_V_52_reload),
    .din3(com_1_reg_837),
    .dout(tmp_8_fu_541_p5)
);

compute_mux_32_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_32_16_1_1_U84(
    .din0(REG_V_32_reload),
    .din1(REG_V_40_reload),
    .din2(REG_V_48_reload),
    .din3(com_1_reg_837),
    .dout(tmp_9_fu_553_p5)
);

compute_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U85(
    .din0(REG_V_36_reload),
    .din1(REG_V_44_reload),
    .din2(REG_V_52_reload),
    .din3(REG_V_60_reload),
    .din4(indvars_iv1),
    .dout(tmp_s_fu_565_p6)
);

compute_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U86(
    .din0(REG_V_35_reload),
    .din1(REG_V_43_reload),
    .din2(REG_V_51_reload),
    .din3(REG_V_59_reload),
    .din4(indvars_iv1),
    .dout(tmp_4_3_fu_578_p6)
);

compute_mux_32_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_32_16_1_1_U87(
    .din0(REG_V_39_reload),
    .din1(REG_V_47_reload),
    .din2(REG_V_55_reload),
    .din3(com_1_reg_837),
    .dout(tmp_8_3_fu_591_p5)
);

compute_mux_32_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_32_16_1_1_U88(
    .din0(REG_V_35_reload),
    .din1(REG_V_43_reload),
    .din2(REG_V_51_reload),
    .din3(com_1_reg_837),
    .dout(tmp_9_3_fu_603_p5)
);

compute_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
mux_42_16_1_1_U89(
    .din0(REG_V_39_reload),
    .din1(REG_V_47_reload),
    .din2(REG_V_55_reload),
    .din3(REG_V_63_reload),
    .din4(indvars_iv1),
    .dout(tmp_10_3_fu_615_p6)
);

compute_mul_mul_16ns_16ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16ns_16ns_32_4_1_U90(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_660_p0),
    .din1(grp_fu_660_p1),
    .ce(1'b1),
    .dout(grp_fu_660_p2)
);

compute_mul_mul_16ns_16ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16ns_16ns_32_4_1_U91(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_666_p0),
    .din1(grp_fu_666_p1),
    .ce(1'b1),
    .dout(grp_fu_666_p2)
);

compute_mul_mul_16ns_16ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16ns_16ns_32_4_1_U92(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_672_p0),
    .din1(grp_fu_672_p1),
    .ce(1'b1),
    .dout(grp_fu_672_p2)
);

compute_mul_mul_16ns_16ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16ns_16ns_32_4_1_U93(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_678_p0),
    .din1(grp_fu_678_p1),
    .ce(1'b1),
    .dout(grp_fu_678_p2)
);

compute_mac_muladd_16ns_16ns_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16ns_16ns_32ns_32_4_1_U94(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_684_p0),
    .din1(grp_fu_684_p1),
    .din2(grp_fu_660_p2),
    .ce(1'b1),
    .dout(grp_fu_684_p3)
);

compute_mac_muladd_16ns_16ns_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16ns_16ns_32ns_32_4_1_U95(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_693_p0),
    .din1(grp_fu_693_p1),
    .din2(grp_fu_666_p2),
    .ce(1'b1),
    .dout(grp_fu_693_p3)
);

compute_mac_muladd_16ns_16ns_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16ns_16ns_32ns_32_4_1_U96(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_702_p0),
    .din1(grp_fu_702_p1),
    .din2(grp_fu_672_p2),
    .ce(1'b1),
    .dout(grp_fu_702_p3)
);

compute_mac_muladd_16ns_16ns_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16ns_16ns_32ns_32_4_1_U97(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_711_p0),
    .din1(grp_fu_711_p1),
    .din2(grp_fu_678_p2),
    .ce(1'b1),
    .dout(grp_fu_711_p3)
);

compute_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln79_fu_375_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            com_fu_118 <= add_ln79_fu_381_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            com_fu_118 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        com_1_reg_837 <= ap_sig_allocacmp_com_1;
        com_1_reg_837_pp0_iter1_reg <= com_1_reg_837;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        com_1_reg_837_pp0_iter2_reg <= com_1_reg_837_pp0_iter1_reg;
        com_1_reg_837_pp0_iter3_reg <= com_1_reg_837_pp0_iter2_reg;
    end
end

always @ (*) begin
    if (((icmp_ln79_fu_375_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_com_1 = 2'd0;
    end else begin
        ap_sig_allocacmp_com_1 = com_fu_118;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        buffer_2_ce0 = 1'b1;
    end else begin
        buffer_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        buffer_2_ce1 = 1'b1;
    end else begin
        buffer_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (phase_read_reg_733 == 1'd1))) begin
        buffer_2_we0 = 1'b1;
    end else begin
        buffer_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (phase_read_reg_733 == 1'd1))) begin
        buffer_2_we1 = 1'b1;
    end else begin
        buffer_2_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln79_fu_381_p2 = (ap_sig_allocacmp_com_1 + 2'd1);

assign add_ln87_3_fu_638_p3 = {{i_cast}, {com_1_reg_837_pp0_iter3_reg}};

assign add_ln88_3_fu_649_p3 = {{com_1_reg_837_pp0_iter3_reg}, {i_cast}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign buffer_2_address0 = zext_ln88_fu_655_p1;

assign buffer_2_address1 = zext_ln87_fu_644_p1;

assign buffer_2_d0 = (grp_fu_711_p3 + grp_fu_693_p3);

assign buffer_2_d1 = (grp_fu_702_p3 + grp_fu_684_p3);

assign com_cast_fu_371_p1 = ap_sig_allocacmp_com_1;

assign grp_fu_660_p0 = grp_fu_660_p00;

assign grp_fu_660_p00 = tmp_8_1_fu_405_p5;

assign grp_fu_660_p1 = grp_fu_660_p10;

assign grp_fu_660_p10 = tmp_4_1_fu_387_p6;

assign grp_fu_666_p0 = grp_fu_666_p00;

assign grp_fu_666_p00 = tmp_10_1_fu_437_p6;

assign grp_fu_666_p1 = grp_fu_666_p10;

assign grp_fu_666_p10 = tmp_9_1_fu_421_p5;

assign grp_fu_672_p0 = grp_fu_672_p00;

assign grp_fu_672_p00 = tmp_8_2_fu_473_p5;

assign grp_fu_672_p1 = grp_fu_672_p10;

assign grp_fu_672_p10 = tmp_4_2_fu_455_p6;

assign grp_fu_678_p0 = grp_fu_678_p00;

assign grp_fu_678_p00 = tmp_10_2_fu_505_p6;

assign grp_fu_678_p1 = grp_fu_678_p10;

assign grp_fu_678_p10 = tmp_9_2_fu_489_p5;

assign grp_fu_684_p0 = grp_fu_684_p00;

assign grp_fu_684_p00 = tmp_8_fu_541_p5;

assign grp_fu_684_p1 = grp_fu_684_p10;

assign grp_fu_684_p10 = tmp_4_fu_528_p6;

assign grp_fu_693_p0 = grp_fu_693_p00;

assign grp_fu_693_p00 = tmp_s_fu_565_p6;

assign grp_fu_693_p1 = grp_fu_693_p10;

assign grp_fu_693_p10 = tmp_9_fu_553_p5;

assign grp_fu_702_p0 = grp_fu_702_p00;

assign grp_fu_702_p00 = tmp_8_3_fu_591_p5;

assign grp_fu_702_p1 = grp_fu_702_p10;

assign grp_fu_702_p10 = tmp_4_3_fu_578_p6;

assign grp_fu_711_p0 = grp_fu_711_p00;

assign grp_fu_711_p00 = tmp_10_3_fu_615_p6;

assign grp_fu_711_p1 = grp_fu_711_p10;

assign grp_fu_711_p10 = tmp_9_3_fu_603_p5;

assign icmp_ln79_fu_375_p2 = ((com_cast_fu_371_p1 == i) ? 1'b1 : 1'b0);

assign phase_read_reg_733 = phase;

assign zext_ln87_fu_644_p1 = add_ln87_3_fu_638_p3;

assign zext_ln88_fu_655_p1 = add_ln88_3_fu_649_p3;

endmodule //compute_compute_Pipeline_VITIS_LOOP_79_2
